### PR TITLE
[pt] Fixed 2 FPs and removed "temp_off" from rule ID:QUALQUER_QUE_SEJA

### PR DESCRIPTION
**Pull request by marcoagpinto**
Heya, Susana and Pedro,

Here are the whole results:
https://internal1.languagetool.org/regression-tests/via-http/2023-11-06/pt-BR_full/result_style_QUALQUER_QUE_SEJA%5B1%5D.html

I have removed the two false positives in this pull request:
```
<example>Maria é uma pessoa muito espontânea; explode por qualquer que seja o motivo.</example>
<example>...heiro que mais me remete à minha mãe é o do perfume dela: sempre forte, com presença e notas doces (qualquer que seja o do momento... rs).</example>
```

### CODE REVIEW

**Comment by marcoagpinto** [comment]
Heya, @susanaboatto 

I have added the "formal" to it.

**Comment by marcoagpinto** [comment]
Heya, @susanaboatto and @p-goulart 

I have 7 open pull requests.

Should I wait until they are all approved, or shall I continue adding new ones?

Thanks!

**Comment by p-goulart** [comment]
> I have 7 open pull requests.
> Should I wait until they are all approved, or shall I continue adding new ones?

Sorry about that, I've been focussing on the dictionary migration, but I'll have a look at your PRs now.

**Review by p-goulart — APPROVED** [review]

**Comment by marcoagpinto** [comment]
Thank you, @p-goulart

**Pull request merged**
