### PR TITLE
Pull requedst for changes in the sk language

### PR DESCRIPTION
**Pull request by milossramek**
This is my first pull request - I hope that it is OK, the "./build.sh languagetool-standalone package' finished without failures
--
milos

### CODE REVIEW

**Comment by danielnaber** [comment]
Thanks! Is it on purpose that in `Slovak.java` you only specify `grammar-typography.xml` as a rule file? Because that means the other XML grammar files will be ignored (and if I add them, I get test errors).

**Comment by milossramek** [comment]
Dear Daniel,

I apologize, this was not on purpose. Thank you for noticing that.
Now I get more rule errors, so I have to correct them first.
I'll try to correct it as soon as possible and will ask for pull request
again
Milos


On 2015-03-23 11:30, Daniel Naber wrote:
> Thanks! Is it on purpose that in `Slovak.java` you only specify `grammar-typography.xml` as a rule file? Because that means the other XML grammar files will be ignored (and if I add them, I get test errors).
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/languagetool-org/languagetool/pull/245#issuecomment-84936742
> 


-- 
Milos Sramek, msramek22@gmail.com

**Comment by milossramek** [comment]
On 2015-03-23 11:30, Daniel Naber wrote:
> Thanks! Is it on purpose that in `Slovak.java` you only specify `grammar-typography.xml` as a rule file? Because that means the other XML grammar files will be ignored (and if I add them, I get test errors).
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/languagetool-org/languagetool/pull/245#issuecomment-84936742
> 
Dear Daniel,
did you mean the grammar-nezaradene.xml file? These are untested rules -
I want to move them later to other files, which will be included. I
first thought that grammar.xml was the missing file, so I included that
first - test started to fail with weird messages :)

best
Milos



-- 
Milos Sramek, msramek22@gmail.com

**Comment by danielnaber** [comment]
I meant both, but adding only grammar.xml also throws errors, as you say.

**Comment by danielnaber** [comment]
Can you do the fixes before the release? The release is going to be on Monday, so the last day I'd like to merge such changes would be Saturday.

**Comment by milossramek** [comment]
On 2015-03-26 09:35, Daniel Naber wrote:
Dear Daniel,

there is nothing to fix on my side,
./build.sh languagetool-standalone clean package
finishes without errors and I have nothing to push

I unfortunately got sick and was not able to improve the existing slovak
rules. Next time - when will be the next release?

best
Milos

> Can you do the fixes before the release? The release is going to be on Monday, so the last day I'd like to merge such changes would be Saturday.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/languagetool-org/languagetool/pull/245#issuecomment-86402262
> 


-- 
Milos Sramek, msramek22@gmail.com

**Comment by danielnaber** [comment]
I think the tests work for me too, but not if I add grammar.xml to RULE_FILES in Slovak. I understand that rules are missing if grammar.xml is not included? Anyway, the next release after 2.9 will be in three months, but your changes can be online on languagetool.org as soon as they are merged and we also build nightly snapshots from the latest code, so the release isn't that important I think.

**Comment by milossramek** [comment]
On 2015-03-29 16:55, Daniel Naber wrote:
> I think the tests work for me too, but not if I add grammar.xml to RULE_FILES in Slovak. I understand that rules are missing if grammar.xml is not included? Anyway, the next release after 2.9 will be in three months, but your changes can be online on languagetool.org as soon as they are merged and we also build nightly snapshots from the latest code, so the release isn't that important I think.

The grammar.xml is included, as shown by the tests:

Running org.languagetool.rules.sk.SlovakPatternRuleTest
Running XML validation for sk/grammar.xml...
Running XML validation for sk/grammar-typography.xml...

It looks like that grammar.xml is loaded somewhere else in the code. I
did that in exactly the same way as in the Ukrainian language.

best
Milos

> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/languagetool-org/languagetool/pull/245#issuecomment-87423364
> 


-- 
Milos Sramek, msramek22@gmail.com

**Comment by danielnaber** [comment]
Hi Milos, sorry, I was confused. grammar.xml had been there all the time because we call `super.getRuleFileNames()` and `grammar-nezaradene.xml` can be ignored, as you said. I've merged the patch now and it should be in the next nightly build (https://languagetool.org/download/snapshots/?C=M;O=D) and then also available in the text box on languagetool.org.

**Pull request merged**
