### PR TITLE
[pt] Fixed tons of FPs "nouns -> verbs" in disambiguation.xml

### PR DESCRIPTION
**Pull request by marcoagpinto**
Heya, @jaumeortola , @susanaboatto and @p-goulart 

This is a disambiguator rule to fix nouns appearing as verbs.

I have fixed 4686 false positives while testing against 950 000 sentences.

I just gave a brief look at the .txt, and it appears to be fine, but here it is anyway.

Dummy rule for testing:
```
<rulegroup id='MARCOAGPINTO_DIS_VERBO_SUBSTANTIVO' name="Disambiguator: Converter Verbo para Substantivo">
    <rule>
      <pattern>
        <token postag="V.+" postag_regexp="yes"/>
        <token min='1' max='2' postag="D[AI].+|PP.+|Z0.+" postag_regexp="yes"/>
        <marker>
          <and>
            <token postag="VMIP2S0|VMN02S0|VMSF2S0" postag_regexp="yes"/>
            <token postag="NC.+" postag_regexp="yes"/>
          </and>
        </marker>
      </pattern>
        <message>Regra a testar o Disambiguator.</message>
        <short>Testar o Disambiguator.</short>
        <example correction=''><marker>Quero os marines.</marker></example>
    </rule>
</rulegroup>
```

```
SentenceSourceChecker: org.languagetool.dev.dumpcheck.DocumentLimitReachedException: Maximum number of documents (950000) reached
Portuguese (Portugal): 4686 total matches
Portuguese (Portugal): 949999 total sentences considered
```

[_0.txt](https://github.com/user-attachments/files/17355119/_0.txt)

## Summary by CodeRabbit

- **New Features**
	- Introduced a new disambiguation rule for rare parts of speech in Portuguese.
  
- **Improvements**
	- Updated existing rules for better handling of the adverb "tão" and expanded patterns for compound conjunctions.
	- Enhanced grammar checking capabilities for complex sentence structures.

- **Documentation**
	- Commented out example sentences in the grammar and style files for potential future reference, maintaining structure for clarity. 

- **Formatting**
	- Improved readability and consistency in rule definitions.

### CODE REVIEW

**Comment by jaumeortola** [comment]
@marcoagpinto What happens with the examples that you commented out? Are they now FPs? Can you fix them?

**Comment by marcoagpinto** [comment]
@jaumeortola 

They are false positives now, I believe.

I have been terribly stressed and spend the nights rewriting rules.

Maybe they should be left commented out if they are false positives, and then somewhere in time they are replaced?

Right now, I am finishing rewriting and testing another rule.

**Comment by marcoagpinto** [comment]
I have been basically rewriting pt-PT rules because @p-goulart told me I can approve them myself, so I spend the nights rewriting and approving.

**Comment by marcoagpinto** [comment]
Anyway, I believe the patch only broke three (3) examples?

There is more gain than loss, I believe.

**Review by jaumeortola — APPROVED** [review]

**Comment by marcoagpinto** [comment]
@jaumeortola 

Thank you!

❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ 

I was napping.

😛 😛 😛 😛 😛 😛 😛 

I spend the nights awaken and try to sleep during the days.

**Comment by jaumeortola** [comment]
@marcoagpinto 
I see some issues with this change. 
* There are many FPs in with the rule A_WORD, and other rules. 
* There are some test failures in premium rules. 

We need to revert the disambiguation rule, and do more tests before adding it.

**Comment by marcoagpinto** [comment]
@jaumeortola 

Please revert it if you can.

I have been since 4am fixing the FPs, but they are too many for me to handle all at once.

It may take more than a day... my guess is that it may take days to review everything.

Thank you!

**Comment by marcoagpinto** [comment]
@jaumeortola 

I found the "revert" button and created a pull request to revert it.

I am looking at the results and I need a few days to fix them.

Thanks!

**Pull request merged**
