### PR TITLE
[pt-PT] Added rule ID:SIMPLIFICAR_A_SER_PP_A_INF

### PR DESCRIPTION
**Pull request by marcoagpinto**
Heya,

A brand-new rule for pt-PT.

Follow the discussion here:
https://github.com/languagetool-org/languagetool/issues/9622

Thanks!

### CODE REVIEW

**Comment by marcoagpinto** [comment]
@susanaboatto @p-goulart 

Why did the test fail?

Help!

**Comment by p-goulart** [comment]
> Why did the test fail?

```
Caused by: org.xml.sax.SAXParseException; lineNumber: 3337; columnNumber: 79; The entity "adverbios_de_intensidade" was referenced, but not declared.
```

**Comment by marcoagpinto** [comment]
@p-goulart 

Yes, I forgot the entity.

I have just added it.

Sorry… 😛

**Comment by marcoagpinto** [comment]
Before going to bed, I wrote down on paper: “don't forget to add inflected=yes, verb "haver”" and in the morning I didn't remember to add the entity used by the rule.

😄 😄 😄 😄

**Review by p-goulart — APPROVED** [review]

**Pull request merged**
