### PR TITLE
Added New Words

### PR DESCRIPTION
**Pull request by SethiPandi**
Just wanted to add all words from my personal dictionary which are actually valid English words, and can be found on Wordnik.
- [abandonware](https://www.wordnik.com/words/abandonware)
- [cannoneer](https://www.wordnik.com/words/cannoneer)
- [cannoneering](https://www.wordnik.com/words/cannoneering)
- [chainmail](https://www.wordnik.com/words/chainmail)
- [cheque](https://www.wordnik.com/words/cheque)
- [cheques](https://www.wordnik.com/words/cheques)
- [chequing](https://www.wordnik.com/words/chequing)
- [checksums](https://www.wordnik.com/words/checksums)
- [classpath](https://www.wordnik.com/words/classpath)
- [debuff](https://www.wordnik.com/words/debuff)
- [debuffs](https://www.wordnik.com/words/debuffs)
- [deserialize](https://www.wordnik.com/words/deserialize)
- [deserializer](https://www.wordnik.com/words/deserializer)
- [deserializing](https://www.wordnik.com/words/deserializing)
- [despawned](https://www.wordnik.com/words/despawn)
- [despawning](https://www.wordnik.com/words/despawning)
- [dogpile](https://www.wordnik.com/words/dogpile)
- [DoS](https://www.wordnik.com/words/DoS)
- [duotone](https://www.wordnik.com/words/duotone)
- [enum](https://www.wordnik.com/words/enum)
- [EXIF](https://www.wordnik.com/words/EXIF)
- [inferable](https://www.wordnik.com/words/inferable)
- [interpolator](https://www.wordnik.com/words/interpolator)
- [interpolators](https://www.wordnik.com/words/interpolators)
- [iterable](https://www.wordnik.com/words/iterable)
- [JavaSE](https://www.wordnik.com/words/JavaSE)
- [laggy](https://www.wordnik.com/words/laggy)
- [libre](https://www.wordnik.com/words/libre)
- [loadout](https://www.wordnik.com/words/loadout)
- [mana](https://www.wordnik.com/words/mana)
- [mimesis](https://www.wordnik.com/words/mimesis)
- [minigame](https://www.wordnik.com/words/minigame)
- [minigames](https://www.wordnik.com/words/minigames)
- [misconfigured](https://www.wordnik.com/words/misconfigured)
- [normalities](https://www.wordnik.com/words/normalities)
- [overridable](https://www.wordnik.com/words/overridable)
- [playthrough](https://www.wordnik.com/words/playthrough)
- [queryable](https://www.wordnik.com/words/queryable)
- [rebase](https://www.wordnik.com/words/rebase)
- [rebuy](https://www.wordnik.com/words/rebuy)
- [rebuying](https://www.wordnik.com/words/rebuying)
- [replayability](https://www.wordnik.com/words/replayability)
- [reskin](https://www.wordnik.com/words/reskin)
- [reskinning](https://www.wordnik.com/words/reskinning)
- [rightsholder](https://www.wordnik.com/words/rightsholder)
- [rightsholders](https://www.wordnik.com/words/rightsholders)
- [scorewriter](https://www.wordnik.com/words/scorewriter)
- [spammy](https://www.wordnik.com/words/spammy)
- [src](https://www.wordnik.com/words/src)
- [sublicense](https://www.wordnik.com/words/sublicense)
- [submodule](https://www.wordnik.com/words/submodule)
- [submodules](https://www.wordnik.com/words/submodules)
- [torrenting](https://www.wordnik.com/words/torrenting)
- [transcode](https://www.wordnik.com/words/transcode)
- [transcoding](https://www.wordnik.com/words/transcoding)
- [unescape](https://www.wordnik.com/words/unescape)
- [unescaped](https://www.wordnik.com/words/unescaped)
- [unescaping](https://www.wordnik.com/words/unescaping)
- [wyvern](https://www.wordnik.com/words/wyvern)
- [whistleblowing](https://www.wordnik.com/words/whistleblowing)
- [weeaboo](https://www.wordnik.com/words/weeaboo)

Please let me know if there are any problems!

### CODE REVIEW

**Comment by SethiPandi** [comment]
Added a few extra, just plurals and such.

* [classpaths](https://www.wordnik.com/words/classpaths)
* [despawn](https://www.wordnik.com/words/despawn)
* [dogpiles](https://www.wordnik.com/words/dogpiles)
* [dogpiled](https://www.wordnik.com/words/dogpiled)
* [enums](https://www.wordnik.com/words/enums)
* [playthroughs](https://www.wordnik.com/words/playthroughs)
* [reskins](https://www.wordnik.com/words/reskins)
* [scorewriters](https://www.wordnik.com/words/scorewriters)
* [sublicensing](https://www.wordnik.com/words/sublicensing)
* [transcodes](https://www.wordnik.com/words/transcodes)
* [transcodings](https://www.wordnik.com/words/transcodings)
* [unescapes](https://www.wordnik.com/words/unescapes)
* [wyverns](https://www.wordnik.com/words/wyverns)
* [weeaboos](https://www.wordnik.com/words/weeaboos)

**Comment by SethiPandi** [comment]
Sorry to spam, just wanted to fit this here as well since I just used it. ^-^' 

* [MMORPGs](https://www.wordnik.com/words/MMORPGs)

**Comment by SethiPandi** [comment]
_ahem_ And again...

* [monospace](https://www.wordnik.com/words/monospace)

**Comment by SethiPandi** [comment]
Yet another word: 

* [togglable](https://www.wordnik.com/words/togglable)

**Comment by tiff** [comment]
@SethiPandi thank you so much. I couldn't merge it just like that because there are some differences in spelling between the different English variations (e.g. sublicense vs sublicence). Also, some words don't exist in the official dictionaries that we use as a reference (Collinsdictionary, Lexico, Merriam-Webster).

I added most words except for these:

* chain mail https://www.merriam-webster.com/dictionary/chain%20mail
* cheque (It is British English for "check")
* classpath
* classpaths
* debuff
* debuffs
* despawn
* despawned
* despawning
* enum
* enums
* mana (easily confused with "man a" and "mama")
* manas 
* normalities (british english)
* overridable
* playthrough
* playthroughs
* queryable
* rightsholder (Wikipedia only knows "rights holder")
* rightsholders
* scorewriter
* scorewriters
* togglable
* torrenting
* weeaboo
* weeaboos

Feel free to post your dictionary here from time to time. Our dictionary is far from being complete.

**Comment by SethiPandi** [comment]
Thanks for that! Sorry for mishaps also; I'll try to get more familiar, and make future PRs fit the structure better.
Can I just verify, sorry if this information is public, are there any dictionaries other than the three names above that you guys use for reference?

Of the dictionaries named above, Collins appears to be the only one that accepts word submissions openly. Should any of the words above be accepted, except words that were excluded for other reasons, would I be welcome to try add them in a separate PR?

**Pull request closed without merging**
