### PR TITLE
Revert "Memory and performance optimizations"

### PR DESCRIPTION
**Pull request by SteVio89**
Reverts languagetool-org/languagetool#11027 → caused issues with premium need to fix those first

### CODE REVIEW

**Comment by hurricup** [comment]
@SteVio89 how can I investigate this premium thing? And why there are no tests for it in common repo? Or isn't it possible to test without some close source code?

**Comment by hurricup** [comment]
Maybe you could set up some CI I could use for testing? Still may be tricky to fix without tests and/or code. Btw, it is possible things that failing are those direct field accesses I replaced with getInstance

**Comment by SteVio89** [comment]
@hurricup Unfortunately you cannot test this by yourself and this case also required the close source code.

I will update your code, hopefully by Friday. We have CI to tests against the premium, but only for our master branch, and the test results are only available with access to the premium branch.

Here is the new PR https://github.com/languagetool-org/languagetool/pull/11044 I will update this with my changes ASAP.

**Comment by hurricup** [comment]
How do we proceed with the next changes? Because there are more like this one.

**Comment by SteVio89** [comment]
Just create the PR as usual and I will check everything against premium before the merge :)

**Pull request merged**
