### PR TITLE
[pt] improve no verb rule

### PR DESCRIPTION
**Pull request by tiff**
@marcoagpinto is this what you meant?

Can you provide some example sentences where one of the "ção" words is used as a verb?

### CODE REVIEW

**Comment by tiff** [comment]
Some more words I found that could be part of the list:
* relação
* validação
* instalação
* resolução
* comunicação
* solicitação
* manutenção
* personificação

**Comment by marcoagpinto** [comment]
@tiff 

Duração das batalhas até 10 horas.

“Operação Tempestade no Deserto” contra o Iraque em 1991.

O estudo de métodos de redução de dados.

Gestão Regional de Conservação.

The above is from my thesis.

Then,  I need to find a way to solve the following false positives:
Esta técnica falha 5 em cada 1000 ocorrências.
Mudanças no comportamento, personalidade ou modo de pensar.
Sistema de Crenças: São os argumentos e os pesos.

falha (verb falhar), pensar (verb pensar), são (verb ser).

How can it fail with these three common verbs?

**Comment by tiff** [comment]
@marcoagpinto none of the sentences you provided cause an error with the current version (without my changes)
Bildschirmfoto 2019-11-08 um 11 13 33

**Comment by marcoagpinto** [comment]
@tiff 

Those no longer appear as errors with my change last week, but I need to create some exceptions for female nouns ending with "ção" which I saw in the nightly diff.

The exceptions found in the nightly diff are the ones I placed in a line which I haven't been able to code and asked for your help.

**Comment by tiff** [comment]
Ok, I was asking for sentences that I can verify my changes with. Do you have them? Where is the nightly diff you're referring to?

**Comment by marcoagpinto** [comment]
@tiff 
https://internal1.languagetool.org/regression-tests//20191102/result_pt-PT_20191102.html

See there the noun "vegetação" which is not a verb derivation and so it must be added to the exceptions:
"Vegetação de clima frio: coníferas no sul da Argentina e do Chile."

**Comment by tiff** [comment]
@marcoagpinto ok, I think I misunderstood you. You want to ignore words that end with "ção" except the ones listed in `substantivos_nao_verbais`

**Comment by marcoagpinto** [comment]
@tiff 
It is the opposite:
substantivos_nao_verbais (non_verbal_nouns)
is the list of words that are not verbal nouns, "vegetação" is there and so it shouldn't be used as a verb.

**Comment by marcoagpinto** [comment]
ahhh... sorry... I can't explain myself clearly.

The words in that file should trigger that the sentence has no verb.

**Comment by marcoagpinto** [comment]
because there are no common verbs using these words.

**Comment by marcoagpinto** [comment]
But, for example:
"A vegetação é curta"
vegetação= no verb
é = verb "ser"
In this case it is a valid sentence.

**Comment by marcoagpinto** [comment]
@tiff 
Did my attempt to explain help?

Could you merge your code if it is so?

Thanks!

**Comment by marcoagpinto** [comment]
@tiff 
I pressed the "Merge" button.

Tomorrow I will check if it requires improvements.

**Comment by tiff** [comment]
@marcoagpinto my code was not correct because I misunderstood you! please give me a little time to look into this.

**Pull request merged**
