### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by yobels**
This link contain page not found https://sourceforge.net/projects/tattoi.u/files/Trigram%20Text/ ,The alternative way from http://www.sttmedia.com/syllablefrequency-filipino that contain trigram data

### CODE REVIEW

**Comment by jayvdb** [comment]
I dont see Tagalog at http://storage.googleapis.com/books/ngrams/books/datasetsv2.html

**Comment by yobels** [comment]
my apologize, Sir, i'm too concern about trigram and forget about the
tagalog itself, so it wasn't correct, am i still have permission to fix up
my pr or i am not passed Mr. John? i am trying to find the correct link
again or find another pr.

**Comment by danielnaber** [comment]
The new URL seems to be 3gram data for the character level. Also, they don't seem to be under a free license. I'm not even sure what the original comment in the README (with the broken link) was referring to.

**Comment by jayvdb** [comment]
It comes from rev6041 , by user [tattoi](https://sourceforge.net/u/tattoi/profile/), which may be @tattoi.

I cant find it online anywhere now.  Perhaps this URL should be removed from the readme?

**Pull request closed without merging**
