### PR TITLE
Improve "suppress misspelled"

### PR DESCRIPTION
**Pull request by jaumeortola**
Improve the attribute `suppress_misspelled` according to #2787.

### CODE REVIEW

**Comment by danielnaber** [comment]
@jaumeortola I haven't looked at all the details of the code changes, but the tests work and it also works fine on the live system (I deployed it on one server for testing).

**Comment by jaumeortola** [comment]
> @jaumeortola I haven't looked at all the details of the code changes, but the tests work and it also works fine on the live system (I deployed it on one server for testing).

I don't expect further problems. When you say it, I can resolve the conflicts and the merge can be done.

**Comment by danielnaber** [comment]
Yes, please merge your changes.

**Comment by jaumeortola** [comment]
Merged manually: https://github.com/languagetool-org/languagetool/commit/666e61ad0cc1e1900221cac2a3e92e66bef40191 and following.

**Pull request closed without merging**
