### PR TITLE
[en] improve ONES rule antipattern

### PR DESCRIPTION
**Pull request by Clex**
This fixes false positives with "loved ones" + noun, such as "give your loved ones money".

It's my first pull request on languagetool, please let me know if I can improve something!

### CODE REVIEW

**Comment by danielnaber** [comment]
Thanks for your PR. There's currently a test failure:

```
Test failure for rule ONES[1] in file /org/languagetool/rules/en/grammar.xml: Carer information: how to care for your loved ones feet."
Errors expected: 1
Errors found   : 0
Message: Did you mean <suggestion>one's</suggestion>?
Analyzed token readings: [/SENT_START*] Carer[carer/NN*,B-NP-singular]  [ /null*] information[information/NN:U,E-NP-singular] :[:/:*,:/PCT*,O]  [ /null*] how[how/WRB,B-ADVP]  [ /null*] to[to/IN,to/TO,B-VP]  [ /null*] care[care/NN:UN,care/VB,care/VBP,I-VP]  [ /null*] for[for/CC,for/IN,for/RP,B-PP]  [ /null*] your[your/PRP$,B-NP-plural]  [ /null*] loved[love/VBD,love/VBN,I-NP-plural]  [ /null*] ones[one/NNS,I-NP-plural]  [ /null*] feet[foot/NNS,E-NP-plural] .[./.*,./SENT_END*,./PCT*,O]
Matches: []
```

You can use https://community.languagetool.org/ruleEditor/expert to test your rule for syntax issues and false alarms.

**Comment by Clex** [comment]
Thanks for the link! I used it to fix the rule. The false positive I had doesn't get triggered anymore but I believe there's room for improvement.

I see that another test has failed, can I do something about that?

**Comment by danielnaber** [comment]
The other failure was a temporary GitHub issue it seems. Could you also add an `<example>`, so it becomes clear in the rule itself why this change was made?

**Comment by Clex** [comment]
> The other failure was a temporary GitHub issue it seems. Could you also add an `<example>`, so it becomes clear in the rule itself why this change was made?

Done!

**Comment by danielnaber** [comment]
Is there any specific reason the pattern is `NN.U` and not `NN:U`? Can there be another character than `:`?

**Comment by Clex** [comment]
No, you're right. It's fixed.

**Pull request merged**
