### PR TITLE
[sr] Updated Serbian dictionaries; introduced Ekavian and Jekavian Serbian dialects

### PR DESCRIPTION
**Pull request by strn**

### CODE REVIEW

**Comment by danielnaber** [comment]
The feature freeze for LT 4.0 will be in a few days (http://wiki.languagetool.org/roadmap), so please let me know when you think this is ready. If we miss the feature freeze, this would have to wait for after LT 4.0.

**Comment by strn** [comment]
This is ready right now to be merged.

**Comment by danielnaber** [comment]
Thanks, this has been merged now.

**Comment by dorotafilipczuk** [comment]
Hi @strn, what is your email address?

**Pull request closed without merging**
