### PR TITLE
Update grammar.xml

### PR DESCRIPTION
**Pull request by Mility**
Add a rule:UNCOUNTABLE_PLURAL

### CODE REVIEW

**Comment by danielnaber** [comment]
I suggest you get confirmation from native speakers for your rules. For example, "conscious of the damages" is a very common phrase (see Google) and it doesn't sound wrong to me.

**Comment by Mility** [comment]
See reference: Sidorov, G., Gupta, A., Tozer, M., Catala, D., Catena, A., & Fuentes, S. (2013). Rule-based System for Automatic Grammar Correction Using Syntactic N-grams for English Language Learning (L2). CoNLL-2013, 96. 
page 98.

**Comment by danielnaber** [comment]
The rule would still give a false alarm for `She was awarded $284,000 in damages.` (see http://english.stackexchange.com/questions/29203/damage-vs-damages)

**Comment by Mility** [comment]
Oh. Could we add this exception?

**Comment by danielnaber** [comment]
This was just one example, maybe there are more. Have you tested the rule against Wikipedia and Tatoeba sentences?

**Comment by Mility** [comment]
Sorry, For some reasons, I don't have those big data(Wikipedia and Tatoeba) and the hardware environment to test rule, I only test it in ruleEditor.

**Comment by dpelle** [comment]
> For some reasons, I don't have those big data(Wikipedia and Tatoeba)

Tatoeba sentences can be downloaded with:

  $ wget http://downloads.tatoeba.org/exports/sentences.tar.bz2 
  $ tar jxvf sentences.tar.bz2 

It contains sentences in many languages.
You extract sentences in one language only (English in example below) with:

  $ perl -F'\t' -ane 'print "@F[2 .. $#F]" if ($F[1] eq "eng")' sentences.csv > sentences-eng.csv

It currently contains 565,318 sentences in English. You can truncate it if that's too much for you.

**Comment by Mility** [comment]
Thank you very much.

**Comment by howlinghuffy** [comment]
From my point of view as a native speaker, both 'damages' and 'freedoms' are legitimate in some cases

**Pull request closed without merging**
