### PR TITLE
[pt] Added rule ID:BÁSICO_ELEMENTAR

### PR DESCRIPTION
**Pull request by marcoagpinto**
Heya, @susanaboatto and @p-goulart 

Here is one of the rules I was going to work on the weekend.

```
Portuguese (Portugal): 113 total matches
Portuguese (Portugal): 811129 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```

[_REGRAS_1e2_20.txt](https://github.com/languagetool-org/languagetool/files/13635040/_REGRAS_1e2_20.txt)

### CODE REVIEW

**Comment by p-goulart** [comment]
Looking at the APs and exceptions here, I don't see much to suggest we won't trigger this rule when chemists write about alkali.

> A teoria de Arrhenius limita-se a substâncias que reagem em meio aquoso e não explica o **comportamento básico** de algumas substâncias

> Para tal, use uma **solução básica**.

> atuando como ácido de Lewis em **meio básico**

**Comment by marcoagpinto** [comment]
@p-goulart 

Pedro,

I have added the exceptions you suggested.

❤️ ❤️ ❤️ ❤️  😋 😋 😋 😋 😛 😛 😛 😛

**Comment by p-goulart** [comment]
Okay, let's see how it performs live.

But I'm not convinced that we can reliably tell apart domain-specific uses of 'básico' from the ones that can be replaced with 'elementar' with just the word list you've provided. (Or any word list.)

Those were just a couple of examples from a cursory look at chemistry articles. When I look at common collocates for 'alcalino', I see some things that should definitely be here, like `pH`, `sangue`, `proteína`, `solo`, etc. Definitely some more research is needed.

**Comment by marcoagpinto** [comment]
Thank you, Pedro.

While developing the rule, I had to limitate myself to the results provided by `pt-BR.txt`.

More words can be added to the rule as they come by.

**Pull request merged**
