### PR TITLE
fix #404 - add support for languageModel option in HTTPServer

### LINKED ISSUE #404: HttpServer from commandline ignores languagemodel option
Hello, I am trying to use ngram data on my LT server from the comandline on Windows. I am launching the server like this:

java -cp languagetool-server.jar org.languagetool.server.HTTPServer --port 8081 --langaugemodel "C:\LanguageTool-ngrams"

Where the LanguageTool-ngrams is a folder containing the ngram data (en folder for the english data).

I send one of the test senences to the server:

http://localhost:8081/?language=en&text=Alabama has for of the world's largest stadiums

And I get no errors:
<?xml version="1.0" encoding="UTF-8"?>
<matches software="LanguageTool" version="3.2" buildDate="2015-12-29 10:24">
<language shortname="en" name="English"/>
</matches>

I can verify that ngram data is being used by running the LT gui, in which case all the test senteces result in the expected errors

### PR DESCRIPTION
**Pull request by czojo26**

### CODE REVIEW

**Comment by danielnaber** [comment]
Your pull request has conflicts, could you check that?

**Comment by czojo26** [comment]
I think there is no conflicts now and everything is ok.

**Comment by danielnaber** [comment]
Thanks, looks mostly good, but could you have one last look at https://github.com/languagetool-org/languagetool/pull/648/files and fix these issues: The dummy file has two suffixes: `exampleFile.txt.txt `; the `is()` in the test case got replaced with `Is.is()` - I'm not sure why; and there are whitespace changes unrelated to the change.

**Comment by danielnaber** [comment]
Thanks, I've applied it manually to clean up small whitespace issues.

**Pull request closed without merging**
