### PR TITLE
feat[core]: skip reading dictionary when cached one exists

### PR DESCRIPTION
**Pull request by fabrichter**
load dictionary content lazily, when we don't have it already cached
also fixed formatting

### CODE REVIEW

**Comment by danielnaber** [comment]
Would it be possible to get the whitespace changes as a separate commit, to more easily see the real change?

**Comment by fabrichter** [comment]
You can use the hide whitespace setting on GitHub: https://github.com/languagetool-org/languagetool/pull/9546/files?diff=split&w=1

**Comment by danielnaber** [comment]
> You can use the hide whitespace setting on GitHub

But that only helps with real whitespace changes and not with differences in line breaks, e.g.
whitespace

Anyway, Stefan is the reviewer :-)

**Review by SteVio89 — APPROVED** [review]

**Comment by SteVio89** [comment]
Did not see the latest changes before aprove...pls wait

**Review by SteVio89 — APPROVED** [review]

**Pull request merged**
