### PR TITLE
allow tab or semicolon in files: multiword.txt, added.txt, removed.txt

### PR DESCRIPTION
**Pull request by jaumeortola**
Editing manually tab-separated files is annoying and frequently a waste of time because of errors and confusions. 
I suggest allowing both tabs and semicolons. It is not "beautiful", but it can be useful. In the future, we can replace all tabs with semicolons in all files.

### CODE REVIEW

**Comment by jaumeortola** [comment]
Unfortunately, the semicolon is used inside Arabic POS tags. We need to use another character, or make the separator configurable.

**Comment by udomai** [comment]
Argh! I guess `#` and `%` are out of the question. Is `~` accessible enough on EN/ES keyboards? It's okay in DE & FR, I guess (ALT GR + + in DE and ALT GR + 2 in FR)

**Comment by jaumeortola** [comment]
For me, `~` is ALT GR+4. Anyway, I am going to make it configurable, just in case it is needed in the future: 
`[\t;]` by default and `[\t]` for Arabic.

**Comment by jaumeortola** [comment]
Now, a custom separator can be added to the file itself:
`#separatorRegExp=[\t;]`
The default is still the tab. 
See: https://github.com/languagetool-org/languagetool/commit/4c61abf0a79362f4d4ead02c26ea5753897c0ace

**Pull request merged**
