### PR TITLE
Update dumonts/hunspell to 2.1.1

### PR DESCRIPTION
**Pull request by oleschoenburg**
Updates the dependency on https://gitlab.com/dumonts/hunspell-java to the newly released 2.0.0
Removes the redundant re-implementation of `spell`, `suggest` and `add` methods.

relates to #7045

### CODE REVIEW

**Comment by oleschoenburg** [comment]
I'm mainly opening this PR to test the waters. The release is still new and the darwin-arm64 binaries in particular are not tested. If someone has access to a M1 machine: Could you try out running languagetool with hunspell-java 2.0.0 to confirm that it works as expected and solves #7054? :pray:

**Comment by oleschoenburg** [comment]
I think it's already usable with Rosetta x86 emulation but the M1 binary is in the wrong path. I'll fix this today and release a new version, it'd be great if your colleague could then test it again to confirm that the native binary also works as expected.

**Comment by oleschoenburg** [comment]
@danielnaber updated to the newest version. As mentioned above, would be great if you could test again to ensure that it works without x86 emulation too

**Comment by samhutchins** [comment]
@oleschoenburg I've tried this updated patch on an M1 machine without rosetta, and it seems to work fine

**Comment by danielnaber** [comment]
Another test on an M1 and on production look good so far, I'll merge this.

**Pull request merged**
