### PR TITLE
README: Add hints for shallow clone

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
Reducing the number of branches also reduces the download size. Are all [current branches](https://github.com/languagetool-org/languagetool/branches) still needed?

**Comment by danielnaber** [comment]
@yakovru @jaumeortola branches `revert-481-unification` and `updatemorfologik` can be deleted, can't they?

**Comment by danielnaber** [comment]
@stweil  The character after the `5` in the git command is a typo, isn't it?

**Comment by stweil** [comment]
I used backticks in a first version and missed that one. Thanks for catching that – it is fixed now.

**Comment by jaumeortola** [comment]
Yes, `updatemorfologik` can be deleted.

**Comment by yakovru** [comment]
Yes, revert-481-unification  can be deleted.

**Pull request merged**
