### PR TITLE
[en] add names and technical terms to dictionary

### PR DESCRIPTION
**Pull request by tiff**
Many terms that users added to their personal dictionary. 

Contains a fix for https://github.com/languagetool-org/languagetool/issues/1645

### CODE REVIEW

**Comment by danielnaber** [comment]
center: Should we have a rule then that explains centre/center? Same for programme? Just accepting the en-US variant for all other seems problematic.

**Comment by tiff** [comment]
good point. I will remove both terms for now.

**Comment by tiff** [comment]
In Canadian English we don't suggest "centre"
Bildschirmfoto 2019-07-23 um 11 30 07

**Comment by danielnaber** [comment]
"configed" is colloquial for "configured" I guess? I think we should all `#coll` tags to colloquial words now, so that we can later more easily introduce profiles.

**Comment by tiff** [comment]
yes, see https://en.wiktionary.org/wiki/config

**Comment by tiff** [comment]
I have removed the verb form of config for now

**Pull request merged**
