### PR TITLE
Issue 7044 chunker

### PR DESCRIPTION
**Pull request by MikeUnwalla**
@danielnaber, not sure that I used GitHub correctly. I pushed my changes. Then, GitHub told me to open a pull request.

### CODE REVIEW

**Comment by MikeUnwalla** [comment]
@danielnaber , the chunker changes are not yet in LT (snapshot 2022-09-01). What must I do? Click 'Merge pull request'?

**Comment by danielnaber** [comment]
I'll merge them later today.

**Comment by danielnaber** [comment]
This has been merged now.

**Comment by danielnaber** [comment]
I had to roll this back, too many open issue in premium.

**Pull request closed without merging**
