### PR TITLE
[zh] Update zh translations

### PR DESCRIPTION
**Pull request by gensitu**
* Separate into zh-hans and zh-hant
* Correct punctuation error

### CODE REVIEW

**Comment by danielnaber** [comment]
Thanks, have you tried that this actually works, by testing the LibreOffice add-on with this change?

**Comment by danielnaber** [comment]
What's the advantage of having separate files like `desc_en.txt`?

**Comment by gensitu** [comment]
I submitted new commits to make use of LibreOffice's extension documentation which states that descriptions must be linked with `src` and cannot be added within `description.xml`. The problem with the current setup (including the description with the extension name) is that the extension version is hidden because the name is too long.

**Comment by gensitu** [comment]
I have tested this with several language packs and it seems to work.

**Comment by danielnaber** [comment]
Have you also tested this with OpenOffice?

**Comment by gensitu** [comment]
Also tested with OpenOffice. The LO extension schema is identical to the AOO extension schema, so everything works the same.

**Pull request merged**
