### PR TITLE
Added ability to disable categories from server query

### PR DESCRIPTION
**Pull request by howlinghuffy**
This change allows you to use the "disabledCategories" parameter when quering the languagetool server to disable entire categories of rules for the check.

### CODE REVIEW

**Comment by danielnaber** [comment]
Thanks, could you maybe also write a test case for this?

**Comment by howlinghuffy** [comment]
For sure, I will do that.

Also, my modifications currently only apply for regular server checks, not for checks in the bitext mode.  Should the command work for the bitext too?

I haven't implemented it as yet, as it would involve tinkering with some of the languagetool-core components rather than just the languagetool-server code.

**Comment by danielnaber** [comment]
I must say I'm not familiar enough with the bitext mode. If turning off rules also works for bitext mode, I'd guess turning off categories should work as well?

**Comment by danielnaber** [comment]
Implemented, including an `enabledCategories` parameter (useful with `enabledOnly=yes`).

**Pull request closed without merging**
