### PR TITLE
fix #2118

### LINKED ISSUE #2118: Manage HTML entities interpretAs in error checking
Hello,

My text editor use HTML entities. 

For example `&nbsp;` for "non bracking space" or `&eacute;` for "é".

I tried to use AnnotatedTextBuilder to consider HTML entities like markup and use the "interpretAs" parameter to explain what is the markup.

For example : builder.addMarkup('`&eacute;`','é');

The problem is the interpretAs is not taken in account during checking.

Before checking
image

After checking 
image

The problem is the "é" is not underlined. Languagetool just analyse the word "chapatoire".

If I replace the "é" par "e" the checking is good because no usage of "interpretAs"

image

### PR DESCRIPTION
**Pull request by maxiplay**
All tests OK except command line tests that I cannot launch locally.

### CODE REVIEW

**Comment by maxiplay** [comment]
Multiple sentences failed. Will check that.

**Comment by maxiplay** [comment]
Seems my last commit for #2161 has been pushed in this pull request. How do you avoid this behavior and propose an other pull request ?

**Comment by danielnaber** [comment]
> Seems my last commit for #2161 has been pushed in this pull request. How do you avoid this behavior and propose an other pull request ?

I don't know, but I have merged the typo change manually. Thanks! I hope I will soon have time to look at this PR.

**Comment by maxiplay** [comment]
I had to change the logic of AnnotatedText mapping to manage html entities. Don't hesitate to ask clarifications or comments if needed

**Comment by danielnaber** [comment]
manually merged

**Pull request closed without merging**
