### PR TITLE
[en] added style rule for 'merchandize' vs 'merchandise'

### PR DESCRIPTION
**Pull request by tiff**
Hi @MikeUnwalla 

It seems that "merchandize" is a word that is less commonly used and could be replaced by "merchandise". Does that make sense for British English?

### CODE REVIEW

**Comment by MikeUnwalla** [comment]
For BrE, the z spelling is incorrect. It is not a style preference.

The spell checker for BrE should give a warning, but it does not. Thus, although the message "Consider using the more commonly used" is not correct for BrE, the rule finds the error.

**Comment by tiff** [comment]
Okay, so I guess the best solution would be to add "merchandize" to the prohibit.txt for all languages?

**Comment by MikeUnwalla** [comment]
@tiff , Daniel has asked me to make a pos-aware rule.

**Comment by MikeUnwalla** [comment]
@tiff, In September, I wrote: For BrE, the z spelling is incorrect. It is not a style preference.

I was wrong. Sorry. Collins tells me that the z spelling is a variant of the noun: https://www.collinsdictionary.com/dictionary/english/merchandize

So, your rule is our best option.

The 'Merge pull request' button is greyed out. Do you know a possible cause for that?

**Comment by tiff** [comment]
@MikeUnwalla it was a merge conflict. I resolved them. Feel free to merge and/or change the rule.

**Pull request merged**
