### PR TITLE
Add nouns

### PR DESCRIPTION
**Pull request by SethFalco**
Just want to dump my dictionary again, this time I'll do it across multiple smaller PRs. Making the table is a pain, but I also want to present why I think they belong in the repo rather than my personal dictionary. ^-^'

All of them should pass a test of notability, but if a maintainer disagrees with any of them, feel free to say so.

| Noun | Notability | Alexa Rank | ⭐ on GitHub | Links
|---|---|---|---|---
| [ActivityPub](https://activitypub.rocks/) | W3 Standard with many implementers such as Mastodon and PeerTube. | [7,348,995](https://www.alexa.com/siteinfo/activitypub.rocks) |  | [Wikipedia](https://en.wikipedia.org/wiki/ActivityPub), [W3](https://www.w3.org/TR/activitypub/)
| [AdminExile](https://www.richeyweb.com/documentation/2-adminexile) | Plugin for Joomla. | [898,211](https://www.alexa.com/siteinfo/richeyweb.com)
| [Akeeba](https://www.akeeba.com/) | Develops plugins for Joomla and WordPress. | [87,606](https://www.alexa.com/siteinfo/akeeba.com)
| [Anilist](https://anilist.co/) |  | [14,525](https://www.alexa.com/siteinfo/anilist.co)
| ~~[Binance](https://www.binance.com/)~~ |  | [108](https://www.alexa.com/siteinfo/binance.com) | | [Wikipedia](https://en.wikipedia.org/wiki/Binance)
| ~~[Collabora](https://www.collaboraoffice.com/)~~ | Cloud LibreOffice, and significant contributor. | [416,671](https://www.alexa.com/siteinfo/collaboraoffice.com) | | [Wikipedia](https://en.wikipedia.org/wiki/Collabora)
| [Contabo](https://contabo.com/) | VPS provider. | [4,185](https://www.alexa.com/siteinfo/contabo.com)
| [EditorConfig](https://editorconfig.org/) |  | [486,934](https://www.alexa.com/siteinfo/editorconfig.org) | [2.5k](https://github.com/editorconfig/editorconfig)
| [Habitica](https://habitica.com/) |  | [42,965](https://www.alexa.com/siteinfo/habitica.com) | [8.7k](https://github.com/HabitRPG/habitica) | [Wikipedia](https://en.wikipedia.org/wiki/Habitica)
| [OpenShot](https://www.openshot.org/) | Open-source video editor. | [19,894](https://www.alexa.com/siteinfo/openshot.org) | [2.5k](https://github.com/OpenShot/openshot-qt) | [Wikipedia](https://en.wikipedia.org/wiki/OpenShot)
| [Mullvad](https://mullvad.net/) | VPN provider. | [50,741](https://www.alexa.com/siteinfo/mullvad.net) | | [Wikipedia](https://en.wikipedia.org/wiki/Mullvad)
| [KTouch](https://apps.kde.org/ktouch/) | App developed by KDE. |  | [44](https://github.com/KDE/ktouch) | [Wikipedia](https://en.wikipedia.org/wiki/KTouch)
| [OpenMoji](https://openmoji.org/) | Open-source emojis. | [260,059](https://www.alexa.com/siteinfo/openmoji.org) | [2.1k](https://github.com/hfg-gmuend/openmoji)
| [PureOS](https://www.pureos.net/) |  | [602,450](https://www.alexa.com/siteinfo/pureos.net) | | [Wikipedia](https://en.wikipedia.org/wiki/PureOS)
| [Linode](https://www.linode.com/) | VPS provider. | [2,949](https://www.alexa.com/siteinfo/linode.com) | | [Wikipedia](https://en.wikipedia.org/wiki/Linode)
| ~~[Mindustry](https://mindustrygame.github.io/)~~ | Open-source tower defense game. | [937,381](https://www.alexa.com/siteinfo/mindustrygame.github.io) | [13.1k](https://github.com/Anuken/Mindustry) | [Steam](https://store.steampowered.com/app/1127400/Mindustry/)
| [OpenCraft](https://opencraft.com/) | Significant contributors to Open edX. | [1,596,675](https://www.alexa.com/siteinfo/opencraft.com)
| [Flattr](https://flattr.com/) |  | [38,605](https://www.alexa.com/siteinfo/flattr.com) | | [Wikipedia](https://en.wikipedia.org/wiki/Flattr)
| [Libretro](https://www.libretro.com/) |  | [132,050](https://www.alexa.com/siteinfo/libretro.com) | [6.1k](https://github.com/libretro/RetroArch) | [Wikipedia](https://en.wikipedia.org/wiki/Libretro)

### CODE REVIEW

**Comment by tiff** [comment]
Looks good, except for "Binance". It's too close to "finance" ("b" and "f" are very close on common keyboards)

**Comment by SethFalco** [comment]
Understood, I've removed both Binance and Mindustry from the PR.

**Comment by SethFalco** [comment]
While rebasing, I noticed a comment in `spelling_global.txt`.

```
#Collabora #possible misspelling in several languages
```

So, I've also removed Collabora from this PR as well.

**Comment by danielnaber** [comment]
added manually due to conflicts

**Pull request closed without merging**
