### PR TITLE
Update grammar.xml

### PR DESCRIPTION
**Pull request by Mility**

### CODE REVIEW

**Comment by Mility** [comment]
I think keep health is very important. you can do these things as more as possible every day.

**Comment by danielclipnow** [comment]
I don't think "as more as possible" is correct, see e.g. see http://forum.wordreference.com/threads/as-more-as-possible.1912477/

**Comment by danielnaber** [comment]
I don't think "as more as possible" is correct, see e.g. see http://forum.wordreference.com/threads/as-more-as-possible.1912477/

**Comment by Mility** [comment]
Collect and master idioms as more as you can. Learning English idioms is one of the difficulties.

**Comment by danielnaber** [comment]
I think it should be "as much as you can", but a native speaker should comment on that.

**Comment by Mility** [comment]
Thanks so much.

**Pull request closed without merging**
