### PR TITLE
Ported JUnit tests to Junit 4/5.

### PR DESCRIPTION
**Pull request by oriain**
Still a little bit new to GitHub.  Not sure why it's showing four commits.  22773f8 is the "real" commit.  #371

### CODE REVIEW

**Comment by danielnaber** [comment]
Thanks! Several tests seem to be not running anymore with `mvn clean test`, here's a diff, maybe you can make them work again? [junit-diff.txt](https://github.com/languagetool-org/languagetool/files/244048/junit-diff.txt)

**Comment by oriain** [comment]
Added missing Test annotations.  (Pulling and merging other changes added extra commits again.  New commits are 52ca4a0 and 23aaf60.)  Can you run the tests again and let me know if anything is still missing?

**Comment by danielnaber** [comment]
Your changes have been merged, thanks!

**Comment by oriain** [comment]
Happy to contribute. :-)

**Pull request merged**
