### PR TITLE
speedup command line error reporting on large texts

### PR DESCRIPTION
**Pull request by donnerpeter**
don't replace/mark in entire text only to extract a tiny substring afterwards

### CODE REVIEW

**Comment by danielnaber** [comment]
Thanks! Have you measured how much of a difference this makes?

**Comment by donnerpeter** [comment]
Ah sorry. It's about 5 seconds on 10K English sentences with about 1.5K errors

**Comment by danielnaber** [comment]
I assume you measured this more than once, didn't you? I'm asking because I often see a lot of variation between runs when I try to test performance improvements. Also, that's 5 seconds compared to what, i.e. how much is it in percent?

**Comment by donnerpeter** [comment]
Yes, I usually measure several (about 3) runs, more if the difference isn't very visible.
It's 5 seconds as in 35->30 :)

**Pull request merged**
