### PR TITLE
Update disambiguation.xml

### PR DESCRIPTION
**Pull request by Mility**

### CODE REVIEW

**Comment by danielnaber** [comment]
I'm not sure, which problem does this disambiguation solve?

**Comment by milekpl** [comment]
There might be some good results here, as I used NNP as an exception in some places. But let's see what the requester says.

**Comment by Mility** [comment]
I want to tag "The/DT National/NNP Education/NNP Association/NN:UN." turn into
"The/DT National/NNP Education/NNP Association/NNP."

**Comment by danielnaber** [comment]
Yes, I see that in the rule, but why, does it fix some false alarm? I'm not sure if relying on uppercase is a good idea, headlines are often written in uppercase, no matter if it's a proper noun or not.

**Comment by Mility** [comment]
I imitated this disag.

<rule name="NNP + Uppercase NN -&gt; NNP" id="UPPER_NN_NNP">
        <pattern case_sensitive="yes">
            <token inflected="yes" regexp="yes" postag="NNP">\p{Lu}\p{Ll}+</token>
            <marker>
                <token regexp="yes" postag="NN">\p{Lu}\p{Ll}+</token>
            </marker>
        </pattern>
        <disambig postag="NNP"></disambig>
        <example type="ambiguous" inputform="City[&lt;/S&gt;,city/JJ,city/NN]" outputform="City[&lt;/S&gt;,city/NNP]">Kansas <marker>City</marker></example>
        <example type="untouched">Los Angeles</example>
    </rule>

**Comment by Mility** [comment]
<rule name="NNP + Uppercase NN -&gt; NNP" id="UPPER_NN_NNP">
        <pattern case_sensitive="yes">
            <token inflected="yes" regexp="yes" postag="NNP">\p{Lu}\p{Ll}+</token>
            <marker>
                <token regexp="yes" postag="NN">\p{Lu}\p{Ll}+</token>
            </marker>
        </pattern>
        <disambig postag="NNP"></disambig>
        <example type="ambiguous" inputform="City[&lt;/S&gt;,city/JJ,city/NN]" outputform="City[&lt;/S&gt;,city/NNP]">Kansas <marker>City</marker></example>
        <example type="untouched">Los Angeles</example>
    </rule>

**Pull request closed without merging**
