### PR TITLE
[pt] Removed "temp_off" from rule ID:SER_NECESSARIO_NECESSARIO_V2

### PR DESCRIPTION
**Pull request by marcoagpinto**
Heya,

I have removed the "temp_off".

Thanks!

### CODE REVIEW

**Comment by susanaboatto** [comment]
Hi Marco! Before pushing this, would you mind taking a look at these matches?
O efeito espectador introduzido por Darley e Latane (1968) demonstra que o comportamento de grupo faz com que os indivíduos monitorem se os outros pensam que é necessário reagir em uma situação e, assim, basear seu comportamento neste julgamento.

**Comment by susanaboatto** [comment]
Hi Marco! Before pushing this, would you mind taking a look at these matches?

image

image

**Comment by marcoagpinto** [comment]
Sure, @susanaboatto 

I will fix it tonight, and do another pull request at that time.

Probably at 5am.

Thanks!

**Comment by marcoagpinto** [comment]
@susanaboatto 

Heya, I have fixed the FPs you mentioned.
“a cada dia” was “RG”.

😋 😛

**Comment by marcoagpinto** [comment]
Heya, @susanaboatto  and @p-goulart 

May I press “merge” since the three FPs are fixed?

Thanks!

**Comment by susanaboatto** [comment]
Hi @marcoagpinto sure, please merge it

**Review by susanaboatto — APPROVED** [review]

**Comment by marcoagpinto** [comment]
@susanaboatto 

Thank you!

❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Pull request merged**
