### PR TITLE
[en] Add redundancy rules

### PR DESCRIPTION
**Pull request by gensitu**

### CODE REVIEW

**Comment by MikeUnwalla** [comment]
Hi @gensitu , thank you for your contribution.

Please make these changes:
- Use spaces, not tabs, for indentation.
- Use 4 spaces for each indentation level.
- For message text that the user will see, use a single quote mark not a double quote mark. Example: `Consider using '<match no="1"/>.`

I assume that you used the Rule Editor (https://community.languagetool.org/ruleEditor/expert) to make sure that there are not many false warnings.

Optionally, add a marker around the *first* 'correct' example. The marker causes the correct example in the standalone version of LT to have a highlight on the corrected text:
image

**Comment by MikeUnwalla** [comment]
@danielnaber , possibly I did something wrong when I merged the commit. There is now a Travis CI message. Should I ignore the message? If 'no', what must I do?

**Comment by danielnaber** [comment]
@MikeUnwalla there were several issues with the rules that made the tests fail, I have just reverted the changes until they are ready.

**Comment by MikeUnwalla** [comment]
@danielnaber , thanks.

**Pull request merged**
