### PR TITLE
Stop dispositioning of vertical scrolls when expanding the checkbox

### PR DESCRIPTION
**Pull request by Hsankesara**
Fixes issue #908 

By making a contribution to this project, I certify that:
(a) The contribution was created in whole or in part by me and I
have the right to submit it under the open source license
indicated in the file; or

(b) The contribution is based upon previous work that, to the best
of my knowledge, is covered under an appropriate open source
license and I have the right under that license to submit that
work with modifications, whether created in whole or in part
by me, under the same open source license (unless I am
permitted to submit under a different license), as indicated
in the file; or

(c) The contribution was provided directly to me by some other
person who certified (a), (b) or (c) and I have not modified
it.

(d) I understand and agree that this project and the contribution
are public and that a record of the contribution (including all
personal information I submit with it, including my sign-off) is
maintained indefinitely and may be redistributed consistent with
this project or the open source license(s) involved.

Signed-off-by: Heet Sankesara<heetsankesara3@gmail.com>

Stop disposition of vertical scroll when expanding the checkbox in GUI.

### CODE REVIEW

**Comment by Hsankesara** [comment]
I only did some small changes in gui and the error Travis CI is showing  is this ```The job exceeded the maximum time limit for jobs, and has been terminated.``` which I can't relate to the changes i've done.Any suggestions?

**Comment by danielnaber** [comment]
> Any suggestions?

Travis sometimes has temporary issues, you can ignore it in this case.

**Comment by danielnaber** [comment]
Thanks for the PR, but it doesn't really work for me. Using Ubuntu and Nimbus style, I still have the issue. It seems rather random, though, maybe depending on the active Swing look and feel.

**Comment by Hsankesara** [comment]
Maybe but I am using Debian and it's working fine in it.Maybe it varies from OS to OS.

**Comment by danielnaber** [comment]
So you could reproduce the bug and after your fix, it's working okay for you?

**Comment by Hsankesara** [comment]
language_tools_gui_test
As you can see It works fine in my laptop.

**Comment by Hsankesara** [comment]
Thank You @danielnaber .

**Pull request merged**
