### PR TITLE
[pt] Improved rule ID:VERBO_SER_ÚTIL_PARA_SERVIR_PARA

### PR DESCRIPTION
**Pull request by marcoagpinto**
Hi @susanaboatto and @p-goulart ,

Here is another enhancement of an old rule now with more hits.

😛 😛 😛 😛 😛 😛 😛 😛 😛 😛 😛 😛

### CODE REVIEW

**Comment by marcoagpinto** [comment]
Screenshot 2024-07-09 at 22-17-07 ChatGPT

**Comment by susanaboatto** [comment]
Hmm, not sure I agree with GPT on this one. At least in pt-BR, `servir para` implies that the verb that follows describes the whole purpose of something, while `ser útil` sounds to me like an “added benefit” or just one of several other purposes..

**Comment by marcoagpinto** [comment]
@susanaboatto 

Shall I move it to pt-PT?

**Comment by susanaboatto** [comment]
Yes, please 😺

**Comment by marcoagpinto** [comment]
Sure, give me two minutes.

**Comment by marcoagpinto** [comment]
@susanaboatto 

It is done!

In 2025, I will try to revise all the rules I can, replacing obsolete code with recent code, like I have been doing very slowly currently.

**Comment by marcoagpinto** [comment]
Ahhhh… pt-PT, I assume I can press the merge button like @p-goulart said:
https://github.com/languagetool-org/languagetool/pull/10687#pullrequestreview-2144958907

**Pull request merged**
