### PR TITLE
[pt] Moved and improved rules from wordiness.txt to rule ID:QUALQUER_QUE_SEJA_FOSSE_INDEPENDENTEMENTE

### PR DESCRIPTION
**Pull request by marcoagpinto**
Heya,

I moved the rules from wordiness.txt and created an XML rule with a broader scope (more powerful).

### CODE REVIEW

**Comment by marcoagpinto** [comment]
Ahhhh…

```
Portuguese (Portugal): 27 total matches
Portuguese (Portugal): 811110 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```


[3.txt](https://github.com/languagetool-org/languagetool/files/13194972/3.txt)

**Comment by marcoagpinto** [comment]
Heya,

Is there any feedback regarding this rule?

Thanks!

**Comment by susanaboatto** [comment]
Yes, I left a pending request/comment a few days ago.

**Comment by marcoagpinto** [comment]
@susanaboatto 

It is fixed!

**Review by susanaboatto — APPROVED** [review]

**Pull request merged**
