### PR TITLE
Add abbreviated scientific names to global spelling

### PR DESCRIPTION
**Pull request by p-goulart**
I noticed we accept full scientific names (e.g. `Helicobacter pylori`) but not the abbreviated ones (e.g. `H. pylori`), which are common in scientific literature. This PR addresses that.

### CODE REVIEW

**Comment by LucieSteib** [comment]
OMG this is great ⭐

**Comment by p-goulart** [comment]
(cf. [this post](https://languagetooler.slack.com/archives/C03UT0HD6CB/p1710778134237019?thread_ts=1710776506.122819&cid=C03UT0HD6CB) from devOps about the Circle failure)

**Comment by evan-defran-lt** [comment]
See also this issue: https://github.com/languagetool-org/languagetool/issues/10373

**Comment by jaumeortola** [comment]
We had some problems with short words with abbreviations `spp` or `sp`. For example: Shorea spp., Shorea sp., Agave spp., and so on. The solution was to move these names to disambiguation-global.xml so that they were accepted by the spelling rules but not used as suggestions.
If there are problems with the names in this PR, we could do the same.

**Review by jaumeortola — APPROVED** [review]

**Pull request merged**
