### PR TITLE
[pt] Migrate spelling dictionaries to Morfologik format

### PR DESCRIPTION
**Pull request by jaumeortola**
# Migrate PT dictionary to Morfologik

This PR:
- removes the old Hunspell data;
- uses Morfologik-format binary dictionary data hosted on Sonatype;
- adds a bunch of tests (mostly speller and tokeniser);
- moves a lot (not all) of the data from `hunspell/spelling.txt` to `spelling.txt`;
- reworks the tokeniser to use the same break characters as the other locales.

The work with curation of the dictionary source data was done in the `portuguese-pos-dict` repo.

## To do before merging

- [x] compare this branch vs. master with a large corpus;
- [x] resolve problems (caused by tokenization, and others);
- [x] release the new dictionaries;
- [x] remove old Hunspell files and rules;
- [x] add more tests;
- [x] add words to `resource/pt/do_not_suggest.txt`.

---

@jaumeortola , I've taken all the steps to release it. As far as I can see, it's live. But the tests still fail when trying to read the contents of the live repository. This part of it I have no idea about.

@danielnaber , you can already review the Java, I don't reckon it'll change.

@susanaboatto ... lol yeah there's a lot of stuff. Do have a look at the changes made to the disambiguator and the new files (`spelling.txt`, `do_not_suggest.txt`, and `dialect_alternations.txt`). All the other PT-specific changes are really made directly to the dictionary source data in the PT dictionary repo.

---

<sup>Before merging, please let me squash this into something acceptable.</sup>

### CODE REVIEW

**Review by danielnaber — APPROVED** [review]

**Comment by danielnaber** [comment]
> But the tests still fail when trying to read the contents of the live repository. This part of it I have no idea about.

I restarted the CI process and this time it has worked, it seems.

**Comment by p-goulart** [comment]
@SteVio89 this is the PR that @maphjo mentioned yesterday with the partial test deploy for PT dictionaries.

**Comment by p-goulart** [comment]
@SteVio89 the rule ID we had was not being underlined in red – I thought it was enough for it to contain `MORFOLOGIK` but it had to contain `MORFOLOGIK_RULE`. So I've pushed new code with the updated rule ID and, once the tests pass, can we deploy that on the test server? Sorry about that.

**Comment by p-goulart** [comment]
Cannot merge until we work out how to get usage data from partial rollout.

**Comment by p-goulart** [comment]
After yesterday's test deployment:

- I've checked the results on Matomo to make sure we're getting proper data;
- the apply rate of the new rule hovers around 60%; the Hunspell version had ~55%:
Screenshot 2023-12-06 at 9 59 06 AM

I think it's safe to say we can merge this! Big success 🥳 

Thanks @jaumeortola @maphjo @SteVio89 for the support with this endeavour!

**Comment by danielnaber** [comment]
5 more percentage points is great! Thanks to everyone who has been working on this!

**Pull request merged**
