### PR TITLE
add suggestion

### PR DESCRIPTION
**Pull request by Discostu36**
partial fix of  #9264

### CODE REVIEW

**Comment by Luisa-LT** [comment]
Thanks for trying this out! What about the case a user actually wanted to write "schlammig" or "schaumig"?
Bsp:
> Wie war die Party? Sie war sehr schwammig, schlammig und schaumig. :-D

**Comment by Discostu36** [comment]
"schlammig" and "schaumig" would still be in the suggestions, won't they? This is only adding to the suggestions, not replacing them? For example:
https://github.com/languagetool-org/languagetool/blob/bdd98c2bfe1908b0e88901863304e907209242a8/languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/GermanSpellerRule.java#L97 
"leider" and "Lieder" are addded to the suggestions, but LanguageTool ist still also suggesting "wieder", "nieder" and "Dieter".
grafik

**Comment by Luisa-LT** [comment]
That's true, seems like you're absolutely right about that, thanks for the example and let's try it then :)

**Comment by Discostu36** [comment]
grafik

It only kind of worked. "schlammiger" is now gone from the suggestions. Maybe I should overwrite suggestions entirely by adding everything that should be there as an array ("schwammiger", "schlammiger", "schaumiger")?

**Comment by Luisa-LT** [comment]
Thanks for checking so quickly! Yes, perhaps you can try this approach:   ` put("Wasn",  w -> Arrays.asList("Was denn", "Was ein", "Was"));`

**Comment by Discostu36** [comment]
Yes, but with RegEx for the different word forms.

**Pull request merged**
