### PR TITLE
[de] add words

### PR DESCRIPTION
**Pull request by tiff**
@janschreiber what do you think?

### CODE REVIEW

**Comment by janschreiber** [comment]
@danielnaber doesn't want names in the list.

**Comment by janschreiber** [comment]
I have made the file
https://github.com/languagetool-org/languagetool/blob/90e72217d6e4d9cdd3c9d477b31dc9bb5be97d56/languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/names.txt
but it isn't used (yet).

**Comment by tiff** [comment]
@danielnaber how do we deal with names? I think that if we whitelist company names (Facebook, WhatsApp, Samsung, ...) across languages then person and city names should also be included.

**Comment by danielnaber** [comment]
Additionally accepting the words from `names.txt` requires some code changes that are a bit tricky. We could add thew words to `spelling.txt` with `#name` as a tag. But there are some words which are very close to other words, so adding them can easily mask real errors, e.g.

Amper -> Ampere
Holl -> hol (Imperativ "holen")
Imke -> Imker

**Comment by tiff** [comment]
I moved the names to names.txt. Feel free to merge. @danielnaber I like the idea. Shall we exclude words that could potentially mask real errors? If so who takes care?

**Comment by danielnaber** [comment]
I'm okay with that. Thanks!

**Pull request merged**
