### PR TITLE
[en] draft PREVIOUSLY_VBD

### PR DESCRIPTION
**Pull request by AzadehSafakish**
image

Ehh, I want to expand this more with other adverbs that signal past tense, but I struggled with 'already' and 'yesterday.' It's ready to go out, but I may come back to it with more adverbs.

### CODE REVIEW

**Comment by AzadehSafakish** [comment]
You know what, I'm going to expand this with more adverbs for past, progressive, and future tense. Converting to draft for now.

**Comment by udomai** [comment]
That sounds really interesting! Also, you might want to extend a Premium rule of Christopher's named WE_ONCE_VB. More about that in two minutes!

**Comment by tiff** [comment]
You are welcome to update and improve my rule (`WE_ONCE_VB`)

**Comment by AzadehSafakish** [comment]
Moving to premium.

**Pull request closed without merging**
