### PR TITLE
[ga] Add Irish

### PR DESCRIPTION
**Pull request by jimregan**

### CODE REVIEW

**Comment by seananocoistin** [comment]
A Jim, conas atá tú? Conas mar atá ag éirí leat leis an dtionscnamh seo? An bhfuil cabhair de dhíth ort?

**Comment by jimregan** [comment]
@seananocoistin - I'll answer in English as it's the common language for this project.

I had two years to give to this, and they ran out. I have quite a few things that remain to be added, but I have no means of testing them for now (ancient laptop won't run a new enough version of Java). I hope to be able to get something done next month, but if you'd like to take over, be my guest.

**Comment by seananocoistin** [comment]
Hello again. It is a pity that you are so pressed for time but I understand. I am not sure what I can do with this though I will certainly try to help if I can. I work as a translator so I am always interested in any software that improves typing and word processing in Irish.

If you have any advice as to what I can do to help, please let me know.

**Comment by jimregan** [comment]
Oh sure. If you can provide sample sentences with errors and their corrections, that would help greatly -- and if you'd be willing to license them under CC0, that would help kill two birds with one stone.

**Comment by seananocoistin** [comment]
How do I go about adding sentences? Do I do it here? Do you have any idea of how many sentences need to be added to make the software viable?

**Comment by dpelle** [comment]
Seanán Ó Coistín wrote:

> How do I go about adding sentences? Do I do it here?
> Do you have any idea of how many sentences need to be added to make the software viable?

It's about proposing examples of sentences with typical mistakes.
One good way to do it is to create a thread for incorrect sentences
in Irish in the forum. I don't speak Irish, but in English one
could suggest sentences with mistakes and their corrections
like this for example:
```
  I look forward to *see* him. -> I look forward to seeing him.
  *Lets* go there.   -> Let's go there.
  Etc.
```
The more examples, the better, but I would not worry about
the number of sentences. They can be added little by little.

Someone knowledgeable in LanguageTool XML rules and Irish
can then transform those sentences into XML rules.

If you have a link (URL) which explains a given mistake, it can be
useful to provide such a URL, as LanguageTool can show a URL
for further information.

**Comment by seananocoistin** [comment]
Tá an leabhar ar an *bord*. -> Tá an leabhar ar an mbord.
Thosaigh an cruinniú *ag* a 10.00. -> Thosaigh an cruinniú ar a 10.00.
Ní *amháin*. -> Ní hamháin.
I *tús* a shaol. -> I dtús a shaol.
Ba *dúthrachtach* an múinteoir í. -> Ba dhúthrachtach an múinteoir í.
Cosc ar *tobac*. -> Cosc ar thobac.
Is mar *geall* ar sin. -> Is mar gheall ar sin.
Ceithre *bhliain* -> Ceithre bliana.
Ar feadh *scaitheamh*. -> Ar feadh scaithimh.
Ag scríobh *an litir*. -> Ag scríobh na litreach.
Go *déanfadh*. -> Go ndéanfadh.
Roimh an *conradh*. -> Roimh an gconradh.
Chuig an *Coimisiún*. -> Chuig an gCoimisiún.
Roimh *deireadh na bliana*. -> Roimh dheireadh na bliana.

**Comment by seananocoistin** [comment]
i *taobh*. -> i dtaobh.
De *barr*. -> de bharr.
De *bun*. -> de bhun.
Parlaimint na *Eorpa*. -> Parlaimint na hEorpa.
Nár *caill*. -> Nár chaill.
Dá *déarfainn* é. -> Dá ndéarfainn é.
Tá cuid *mór* ann. -> Tá cuid mhór ann.
Gúna *an bhean*. -> Gúna na mná.
Éadaí *an fear*. -> Éadaí an fhir.
Tá sé ina sheasamh ag *bun an tsráid*. ->Tá sé ina sheasamh ag bun na sráide.
Tá sí ag imirt i *lár an pháirc*. -> Tá sí ag imirt i lár na páirce.
Ní *caitheann* siad drugaí. -> Ní chaitheann siad drugaí.
Tá sé ag cur *báisteach*. -> Tá sé ag cur báistí.
Bheadh an Rialtas réidh leis an *freagra*. -> Bheadh an Rialtas reidh leis an bhfreagra.
Ní dóigh liom go *tabharfaí* post dó. -> Ní dóigh liom go dtabharfaí post dó.
Tabhair don *bean* sin é. -> Tabhair don bhean sin é.
Ná *abair* faic faoi. -> Ná habair faic faoi.
Dún do *clab*. -> Dún do chlab.
Dún do *béal*. -> Dún do bhéal.
Tá an *fuinneog* ar oscailt. -> Tá an fhuinneog ar oscailt.
An réamhrá *leis an céad* eagrán. -> An réamhrá leis an gcéad eagrán.
An treoir *le aghaidh* scríbhneoireacht. -> An treoir le haghaidh scríbhneoireacht.

**Comment by seananocoistin** [comment]
Acmhainn *de saghas* a bhí ann. -> Acmhainn de shaghas a bhí ann.
Is *don pobal* atá sé. -> Is don phobal atá sé.
Le haghaidh *an scríbhneoireacht oifigiúil*. -> Le haghaidh na scríbhneoireachta oifigiúla.
Tá sé *sa Eoraip*. -> Tá sé san Eoraip.
*Sa bliain* 2012. -> Sa bhliain 2012.
Céad bliain *ó fhoilsíodh* an leabhar. -> Céad bliain ó foilsíodh an leabhar.
Rinne sé é gan *aon moill*. -> Rinne sé é gan aon mhoill.
Chuaigh siad *i comhairle* a chéile. -> Chuaigh siad i gcomhairle a chéile.
Thug sí *an dhá* leabhar dom. -> Thug sí an dá leabhar dom.
Lorgadh aighneachtaí *ar an pobal*. -> Lorgadh aighneachtaí *ar an bpobal*.
Na daoine *dá tagraítear* san alt. -> Na daoine dá dtagraítear san alt.
D'iarr sí *go cuirfí* leaba ar fáil. -> D'iarr sí go gcuirfí leaba ar fáil.
Gach duine, tusa *go áirithe*. -> Gach duine, tusa go háirithe.
Tabhair cabhair *don foireann*. -> Tabhair cabhair don fhoireann.
Tá buíochas tuillte *ag an fear* sin. -> Tá buíochas tuillte ag an bhfear sin.
Tá *ár buíochas* tuillte acu. -> Tá ár mbuíochas tuillte acu.
*As an cófra*. -> As an gcófra.
*Go éirí* leat. -> Go n-éirí leat.
An toradh *ab fhear*. -> An toradh ab fhearr.
Tá sé *níos fear* anois. -> Tá sé níos fearr anois.
A *gcuid saineolas*. -> A gcuid saineolais.

**Comment by seananocoistin** [comment]
*Mar an céanna*. -> Mar an gcéanna.
*Gan an uisce*. -> Gan an t-uisce.
*Ba ceoltóir* é. -> Ba cheoltóir é.
*ó daltaí* scoile. -> ó dhaltaí scoile.
D'ith mé *roinnt arán* -> D'ith mé roinnt aráin.
Bhuail mé *le Áine* -> Bhuail mé le hÁine.
Lár *na abairte*. -> Lár na habairte.
*Mí na Nollaig*. -> Mí na Nollag.
*Mí na Márta*. -> Mí an Mhárta.
*Sa fhéar*. -> San fhéar.
*Thar an cnoc*. -> Thar an gcnoc.
Tá sé *faoin fógra* mór lasmuigh. -> Tá sé faoin bhfógra mór lasmuigh.
Siúlann sí *ón caisleán* gach lá. -> Siúlann sí ón gcaisleán gach lá.
Tá an madra *sa fraoch*. -> Tá an madra sa fhraoch.
Thug sé *don fear* eile é. -> Thug sé don fhear eile é.
Thit an duilleog *den crann*. -> Thit an duilleog den chrann.
Tháinig an tréad amach *as an gleann*. -> Tháinig an tréad amach as an ngleann.
Thaitin sé leis rothaíocht *faoin grian* bhreá. -> Thaitin sé leis rothaíocht faoin ngrian bhreá.
Chas siad le chéile *roimh an cruinniú*. -> Chas siad le chéile roimh an gcruinniú.
D'eitil an t-éan *thar an fharraige* chiúin. -> D'eitil an t-éan thar an bhfarraige chiúin.
Tá an bhróg *ag an seanmháthair*. -> Tá an bhróg ag an tseanmháthair.
Léim sé amach *tríd an bhfuinneog*. -> Léim sé amach ar an bhfuinneog.
D'iompraigh siad an tolg isteach *tríd an doras*. -> D'iompraigh siad an tolg isteach ar an doras.
Éadaí a chur ar taispeáint *sa fhuinneog*. -> Éadaí a chur ar taispeáint san fhuinneog. 
Tá sé ina shuí *ag an fhuinneog*. -> Tá sé ina shuí ag an bhfuinneog.
Suím *os comhair an tine*. -> Suím os comhair na tine.
Rinne siad achomharc *chun an chúirt*. -> Rinne siad achomharc chun na cúirte.
Tá an dream sin *ag dul chun an Spáinn*. -> Tá an dream sin ag dul chun na Spáinne.
Cuir *sa soitheach* sin é. -> Cuir sa tsoitheach sin é.

**Comment by jimregan** [comment]
That's great! GRMMA

On 13 Jun 2018 9:58 a.m., "Seanán Ó Coistín" <notifications@github.com>
wrote:

*Mar an céanna*. -> Mar an gcéanna.
*Gan an uisce*. -> Gan an t-uisce.
*Ba ceoltóir* é. -> Ba cheoltóir é.
*ó daltaí* scoile. -> ó dhaltaí scoile.
D'ith mé *roinnt arán* -> D'ith mé roinnt aráin.
Bhuail mé *le Áine* -> Bhuail mé le hÁine.
Lár *na abairte*. -> Lár na habairte.
*Mí na Nollaig*. -> Mí na Nollag.
*Mí na Márta*. -> Mí an Mhárta.
*Sa fhéar*. -> San fhéar.
*Thar an cnoc*. -> Thar an gcnoc.
Tá sé *faoin fógra* mór lasmuigh. -> Tá sé faoin bhfógra mór lasmuigh.
Siúlann sí *ón caisleán* gach lá. -> Siúlann sí ón gcaisleán gach lá.
Tá an madra *sa fraoch*. -> Tá an madra sa fhraoch.
Thug sé *don fear* eile é. -> Thug sé don fhear eile é.
Thit an duilleog *den crann*. -> Thit an duilleog den chrann.
Tháinig an tréad amach *as an gleann*. -> Tháinig an tréad amach as an
ngleann.
Thaitin sé leis rothaíocht *faoin grian* bhreá. -> Thaitin sé leis
rothaíocht faoin ngrian bhreá.
Chas siad le chéile *roimh an cruinniú*. -> Chas siad le chéile roimh an
gcruinniú.
D'eitil an t-éan *thar an fharraige* chiúin. -> D'eitil an t-éan thar an
bhfarraige chiúin.
Tá an bhróg *ag an seanmháthair*. -> Tá an bhróg ag an tseanmháthair.
Léim sé amach *tríd an bhfuinneog*. -> Léim sé amach ar an bhfuinneog.
D'iompraigh siad an tolg isteach *tríd an doras*. -> D'iompraigh siad an
tolg isteach ar an doras.
Éadaí a chur ar taispeáint *sa fhuinneog*. -> Éadaí a chur ar taispeáint
san fhuinneog.
Tá sé ina shuí *ag an fhuinneog*. -> Tá sé ina shuí ag an bhfuinneog.
Suím *os comhair an tine*. -> Suím os comhair na tine.
Rinne siad achomharc *chun an chúirt*. -> Rinne siad achomharc chun na
cúirte.
Tá an dream sin *ag dul chun an Spáinn*. -> Tá an dream sin ag dul chun na
Spáinne.
Cuir *sa soitheach* sin é. -> Cuir sa tsoitheach sin é.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/languagetool-org/languagetool/pull/915#issuecomment-396866209>,
or mute the thread

**Comment by seananocoistin** [comment]
Níl a bhuíochas ort. (No need to thank me).

I have a question regarding LanguageTool and identifying the genetive case in Irish.
If for example "éadaí an fear" is typed instead of "éadaí an fhir", can LanguageTool be set up to recognize this? Can a rule be created that if a noun is followed by another noun with the article e.g. éadaí an fhir, Cumann na mBan, Tír na nÓg, etc. then LanguageTool will need to check it? It is the Irish equivalent for "of the". Examples include "barr an tí" (top of the house), "lár na páirce" (the middle of the field), "príomhoide na scoile" (the principal of the school), "Tír na nÓg" (the land of the young people) etc. 

To be more exact, can "x an y" or "x na y" be understood so that LanguageTool knows that x = noun and y = noun so therefore the genetive case applies? If not, then LanguageTool would never be able to understand that *éadaí an fear* is incorrect and it should be **éadaí an fhir**.

**Comment by seananocoistin** [comment]
le *linn an Nollaig*. -> le linn na Nollag
le *linn an cruinniú*. -> le linn an chruinnithe

**Comment by jimregan** [comment]
Yes. It has part of speech tagging, and can flag errors based on attributes
like genitive. The disambiguating needs more work, but I'll be getting
access to a machine I can work with next week, so I can get to it shortly
after that

**Comment by seananocoistin** [comment]
That is great news that the genetive case can be accommated in LanguageTool. There is already an Irish grammar checker called An Gramadóir. It is open source so its files etc. can be used here. That might cut out a lot of work. It can be found here https://www.cadhan.com/gramadoir/

It would be good to have more than one grammar checker for Irish as both of them might help find mistakes that the other misses. I also like that LanguageTool has different languages on its website and has add-ons for various software programs. I hope that when the Irish version is ready that it will be like the way the other languages are.

**Comment by jimregan** [comment]
I know about An Gramadóir - in fact, Kevin Scannell, who created it, gave me permission to use rules from An Gramadóir for LanguageTool, and they make up the bulk of what's done (though there are quite a few left to convert).

**Comment by jimregan** [comment]
One thing LanguageTool can do that An Gramadóir doesn't is dialect-specific rules, which is probably what I'll look into next. In a lot of your examples you have prep + 'AN' + lenited noun, which ought to be eclipsis, unless you're from Ulster. Similarly, Munster Irish also eclipses d and t, so 'ag an ndoras' is correct there.

**Comment by jimregan** [comment]
Yes, supporting the standard is important, and I've spent roughly two years towards getting there. But my own use right now requires dialect-specific rules in addition to standard. It's not one or the other, though: adding, say, dative plurals to the analyser makes it possible to give higher quality suggestions for standard Irish, checking that something like 'i rith na hama' isn't flagged for Ulster Irish naturally entails that is *is* flagged otherwise, etc.

**Comment by jimregan** [comment]
@seananocoistin I've seen on Tuairisc that you've an interest in speech recognition for Irish: the reason I was asking if you'd be willing to license your examples under CC0 was to use them for Common Voice (https://github.com/mozilla/voice-web), which is collecting a speech corpus for multiple languages, Irish included.

**Comment by jimregan** [comment]
@seananocoistin - another way you can help without needing to be a programmer is to move items out of https://github.com/jimregan/languagetool/blob/irishnew/languagetool-language-modules/ga/src/main/resources/org/languagetool/resource/ga/earraidi.txt into https://github.com/jimregan/languagetool/blob/irishnew/languagetool-language-modules/ga/src/main/resources/org/languagetool/resource/ga/people.txt and https://github.com/jimregan/languagetool/blob/irishnew/languagetool-language-modules/ga/src/main/resources/org/languagetool/resource/ga/placenames.txt -- that way, a more specific error message can be generated.
You ought to be able to edit the files in the browser, if not, we'll figure something out.

**Comment by jimregan** [comment]
```
2.) Line 1, column 1, Rule ID: GA_LOGAINM
Message: Logainm Béarla.
Suggestion: Sráid an Mhuilinn
Millstreet 
^^^^^^^^^^ 
```
and
```
2.) Line 1, column 1, Rule ID: GA_PEOPLE
Message: Ainm Béarla.
Suggestion: Néaró
Nero 
^^^^ 
```

**Comment by seananocoistin** [comment]
I am very happy to contribute voice recordings to the Mozilla Common Voices project. This is crucial for the Irish language.

**Comment by jimregan** [comment]
Hmm... at the moment, the two main things I'm working on are getting enhanced-spell-checking style suggestions, and the disambiguation (without that, rules that depend on part of speech will mostly not work), which are mostly things I can automate.
Probably the most pressing thing is to translate the missing messages to Irish (http://wiki.languagetool.org/translating-messages) -- spell checking is incorporated now, but the message is in English, etc.

**Comment by jimregan** [comment]
Thanks for that - I've put through a pull request to Common Voice, you should have received a notification.

**Comment by jimregan** [comment]
@seananocoistin - do you have a better message for this one? 'Ba chóir duit X a scríobh' is my generic go to.
```
2.) Line 1, column 6, Rule ID: PREP_NOUN[1]
Message: Ba chóir duit “báis” a scríobh.
chun bás 
     ^^^ 
```

**Comment by seananocoistin** [comment]
Cad faoi "teacht chun céille" nó "dul chun olcais"?

Is iad ciall agus olcas an dá fhocal sa tuiseal ainmneach ach cuirtear sa
tuiseal ginideach iad i lorg chun.

Ba chóir duit céille a scríobh.

Jim Regan <notifications@github.com> schrieb am Di., 3. Juli 2018, 20:08:

**Comment by seananocoistin** [comment]
"Bíonn ainmfhocail i lorg 'chun' sa tuiseal ginideach."

That could be a more specific way to phrase it rather than "Ba chóir duit X
a scríobh."

Jim Regan <notifications@github.com> schrieb am Di., 3. Juli 2018, 20:08:

**Comment by jimregan** [comment]
> Cad faoi "teacht chun céille" nó "dul chun olcais"?

Well, that's one of the complications when the nominative singular and genitive plural are the same. These will need to have a more specific rule. As is, the rule checks for chun, trasna, timpeall, fearacht, dála, or cois followed by a nominative noun, but not if it could alternatively be a genitive noun form.

**Comment by seananocoistin** [comment]
I thought that that was what you meant for this rule. When a noun comes
after chun, it needs to be in the genitive case.

You will find many examples and extra information here
https://www.teanglann.ie/ga/fgb/chun

*Seanán Ó Coistín*
www.seanan.info
www.twitter.com/seananocoistin
www.instagram.com/seananocoistin
www.linkedin.com/seananocoistin


Tá an ríomhphost seo (agus aon iatán a ghabhann leis) caonda agus rúnda
agus d’fhéadfadh go mbeadh eolas inti atá faoi phribhléid dhlíthiúil. Ní
ceadmhach feidhm a bhaint as an ríomhphost seo d’aon duine ach don té ar
seoladh chuige é. Mura duitse an ríomhphost seo nó an té atá freagrach as é
a sheoladh, tá cosc ar mhacasamhlú agus ar sheachadadh an ríomhphoist seo
agus aon iatán a ghabhann leis chuig aon duine nó feidhm a bhaint as a
bhfuil ann; ní ceart an ríomhphost seo nó aon iatán a léamh. D’fhéadfadh go
mbeadh cosc iomlán dlíthiúil ar sceitheadh nó comhfhreagras nó ar aon
fheidhm a bhaint as ar a bhfuil sa ríomhphost seo gan chead agus
d’fhéadfadh sé a bheith ina chion coiriúil. Má fuair tú an ríomhphost seo
trí bhotún, déan teagmháil leis an té a sheol an ríomhphost seo.


Ar Máirt 3 Iúil 2018 ag 22:30, scríobh Jim Regan <notifications@github.com>:

**Comment by seananocoistin** [comment]
A Jim, an bhfuil aon rud ag tarlú leis seo faoi láthair? An bhfuil sé
beagnach réidh? Cad is féidir liom a dhéanamh?

Seanán

Jim Regan <notifications@github.com> schrieb am Di., 3. Juli 2018, 22:30:

**Comment by seananocoistin** [comment]
Go maith. I hope that it has all gone well. I know how disruptive it can be
to move to another country.

I am happy to help as much as I can. I am not a coder so I am unsure of how
this is meant to be laid out and designed but I am definitely happy to help
with linguistic matters.


*Seanán Ó Coistín*
www.seanan.info
www.twitter.com/seananocoistin
www.instagram.com/seananocoistin
www.linkedin.com/seananocoistin


Tá an ríomhphost seo (agus aon iatán a ghabhann leis) caonda agus rúnda
agus d’fhéadfadh go mbeadh eolas inti atá faoi phribhléid dhlíthiúil. Ní
ceadmhach feidhm a bhaint as an ríomhphost seo d’aon duine ach don té ar
seoladh chuige é. Mura duitse an ríomhphost seo nó an té atá freagrach as é
a sheoladh, tá cosc ar mhacasamhlú agus ar sheachadadh an ríomhphoist seo
agus aon iatán a ghabhann leis chuig aon duine nó feidhm a bhaint as a
bhfuil ann; ní ceart an ríomhphost seo nó aon iatán a léamh. D’fhéadfadh go
mbeadh cosc iomlán dlíthiúil ar sceitheadh nó comhfhreagras nó ar aon
fheidhm a bhaint as ar a bhfuil sa ríomhphost seo gan chead agus
d’fhéadfadh sé a bheith ina chion coiriúil. Má fuair tú an ríomhphost seo
trí bhotún, déan teagmháil leis an té a sheol an ríomhphost seo.


Ar Luan 24 MFómh 2018 ag 07:25, scríobh Jim Regan <notifications@github.com

**Comment by seananocoistin** [comment]
Hi @jimregan. Tá obair thar na mbeart á déanamh agat. How are you getting on?

**Comment by jimregan** [comment]
@seananocoistin Just tidying up what's there for the moment, then finish converting rules from An Gramadóir, then it should be good to go.

**Comment by jimregan** [comment]
@seananocoistin there are still a few hundred rules to go; the simple ones are done, so these ones need a little more prodding to get working.
Once that's done, it might be worth tidying the rules into more meaningful categories, but that's probably a job for somebody else. 
Should be done in about a week or two.

**Comment by jimregan** [comment]
Thanks for the suggestions: and the screenshot, which made it quite clear that I needed to do something about tokenisation

**Comment by jimregan** [comment]
@TiagoSantos81 In the end, it was easier to just add single letters to the additional spell checking dictionary

**Comment by jimregan** [comment]
Replacing this with a newer, tidier pull request

**Pull request closed without merging**
