### PR TITLE
[pt] Improved suggestions in rule ID:SER_SIGNIFICATIVO

### PR DESCRIPTION
**Pull request by marcoagpinto**
Heya,

Just improved the suggestion to also suggest “expressivo”.

The idea came up during sleep.

### CODE REVIEW

**Comment by marcoagpinto** [comment]
> Can we add `is_goal_specific="true"` to this rule? Other than that, it should be ok.

@susanaboatto 

Susana!!!!

Sorry for asking you this, but could I/you press the "Merge pull request" and you directly add that code?

This is the reason I didn't make pull requests in other rule I was working on because I get an error:
Screenshot 2023-10-04 094801

Thanks!

**Comment by marcoagpinto** [comment]
@susanaboatto 

Thank you, I believe I can now press the merge button after the test checks, which were all green.

❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by susanaboatto** [comment]
Done, but FYI: You can also edit smaller changes like this directly on the Github "files changed" page:

image

**Comment by marcoagpinto** [comment]
Ahhhh… “Edit file”, thank you, my dear one!

**Pull request merged**
