### PR TITLE
[ast] New Asturian spelling dict (ast_ES.dict).

### PR DESCRIPTION
**Pull request by esbardu**
Created a new Asturian spelling dict from Hunspell dictionary, removing diminutive and augmentative forms to reduce the file size.
Created a new create_dict2.sh file from original create_dict.sh for using an input file generated with Proofing Tool GUI (detects all compound forms of suffixes).

### CODE REVIEW

**Comment by danielnaber** [comment]
@jaumeortola @esbardu Does this have an impact on memory usage at runtime? We need to be a bit careful here.

**Comment by jaumeortola** [comment]
> Does this have an impact on memory usage at runtime? 

We need to check it out. The new file adds +323 KB. So, at the very least, that amount. 

Moreover, we prefer the new binary dictionaries in external dependencies so as not to make the GitHub repository bigger.

**Comment by esbardu** [comment]
I've tested its functionality adding the file to the LanguageTool LibreOficce extension. I have not noticed any decrease in spelling detection performance. I don't know, however, how may internally affect memory management.
@jaumeortola, where should I allocate the spelling file for not to make bigger the repository? If I allocate it externally, how can LT know the data of the file? Please excuse my ignorance...
The check failed in the "test modules" section, as I can see, because of the Demo text, but I didn't touch anything about that from my last pull request. How can this be possible?

**Comment by esbardu** [comment]
I'm going to review the changes and try to optimize the conversion of Hunspell files.

**Comment by esbardu** [comment]
Well, after trying all changes above, I've solved the circleci checking problems (hard work because of my poor-poor-poor knowledge of Java). I've been simplifying and deleting rules from aff and dic to minimize at maximum the final list of entries. The final ast_ES.dict is a bit bigger that the previous one, but is far smaller than de_DE.dict file, for instace, so I think it will have no problems at runtime. I've checked it in LibreOffice 7.6 and has no performance problems.
The last pending thing is allocating the binary file in a external dependency. Could you please give me some information/link about that, how could I do that and how does it works? Meanwhile, I think it would be a good thing that binary file could be kept inside LT, so I can advance to the next step: the Asturian POStagger file update.

**Comment by danielnaber** [comment]
> The last pending thing is allocating the binary file in a external dependency. Could you please give me some information/link about that, how could I do that and how does it works?

@jaumeortola can maybe help with that

**Comment by esbardu** [comment]
Thanks, Daniel. I'll wait for Jaume's answer. Greetings!El 4 mar 2024 9:46, Daniel Naber ***@***.***> escribió:

The last pending thing is allocating the binary file in a external dependency. Could you please give me some information/link about that, how could I do that and how does it works?

@jaumeortola can maybe help with that

**Comment by jaumeortola** [comment]
@esbardu To create an external dependency, you need to do this: 
- Create a repo (or use the repo where you prepare the dictionaries), and make a structure similar to [this one](https://github.com/languagetool-org/french-pos-dict/) (French dictionary). Copy and adjust `pom.xml` and the `src` folder. I can help you if necessary. This should contain the speller and the tagger dictionaries (French has only the tagger because in French everything is tagged), with the current folder structure in LanguageTool.
- You will need an account in Sonatype to make a release (as explained [here](https://github.com/languagetool-org/french-pos-dict/?tab=readme-ov-file#internal)). To create the account, you will have to look for the information [online](https://help.sonatype.com/en/using-my-sonatype-com.html). This can be time-consuming. Alternatively, we could use an existing organization account (LanguageTool or Softcatalà). That would mean that I would do this step for you if you agreed.

**Comment by esbardu** [comment]
@jaumeortola Thanks so much for your support, Jaume! I think I've done the stuff as you said. Could you please check my repository? Is [this](https://github.com/esbardu/asturian-pos-dict). I've uploaded `ast_ES.dict` speller file inside hunspell directory, as in LanguageTool tree (it's the ultimate file) and `asturian.dict` POStagger file (current LanguageTool file that works with actual grammar rules, but with an major update pending, when I finish classifying all verb enclitics, in a future PR).
About the second part (Sonatype), it would be great if you could allocate the files in LanguageTool or Softcatalà. I belong to Softastur organization, but we haven't got any account in Sonatype.
With all this changes, I understand that I must delete all `.dict` files in the main project, keeping all `.info` and extra files (like `added.txt`, `common_words.txt`, `ignore.txt`, `spelling.txt` and so on). And I should add an ArtifactID item in the `pom.xml` main project file linking to the external dependency, isn't it?

**Comment by jaumeortola** [comment]
@esbardu
It looks good. I will try it locally, and if everything is fine, I will create a new PR with the necessary changes, and I will make a release in Sonatype.

**Comment by esbardu** [comment]
Thank you, Jaume and Daniel for your patience with me.

**Comment by jaumeortola** [comment]
Replaced by https://github.com/languagetool-org/languagetool/pull/10378

**Pull request closed without merging**
