### PR TITLE
Added indonesian grammar.xml

### PR DESCRIPTION
**Pull request by AmdHamdani**
still contain some bugs and misspell words.

### CODE REVIEW

**Comment by danielnaber** [comment]
Thanks. If you keep working on this, it would be great. Please be aware that adding support for a new language causes work for us, so we'll only add new languages once we're sure that they have a long-time, stable maintainership. That means the new language will need to be worked on actively for several months before it can become part of the official version of LT.

**Comment by AmdHamdani** [comment]
Thanks. I will learn indonesian grammar and spelling, and try to maintain this continuously.

**Comment by jayvdb** [comment]
@danielnaber , I am pretty confident that we can pull in the entire list of misspellings from https://id.wikipedia.org/wiki/Wikipedia:Daftar_kosakata_bahasa_Indonesia_yang_sering_salah_dieja in an automated fashion.
To comply with licensing, the grammar file would then need to be Creative Commons Attribution-ShareAlike License, as that is the Wikipedia license.  If that isnt a problem, I'll create an issue for it and our team should be able to provide the fix for it.

**Comment by AmdHamdani** [comment]
@jayvdb Thanks. I forgot to metion it, beside the source from wikipedia I will also use the EBI documentation (https://id.wikipedia.org/wiki/Ejaan_Bahasa_Indonesia) to work with the grammar.

**Comment by danielnaber** [comment]
Also see http://forum.languagetool.org/t/batch-rule-creator-v3-1/1152 for semi-automatic rule creation

**Comment by AmdHamdani** [comment]
@danielnaber thanks for the information, I will learn it.

**Comment by danielnaber** [comment]
I'm closing this so we don't have lingering pull requests, feel free to re-open or open a new request if there's serious support for adding Indonesian.

**Pull request closed without merging**
