### PR TITLE
[ga] add basic support

### PR DESCRIPTION
**Pull request by jimregan**

### CODE REVIEW

**Comment by jimregan** [comment]
Some notes:
Individual commits are here: https://github.com/jimregan/languagetool/tree/ga-basic
There's a pretty complete CG for Irish that I'll be converting. I've only added a single disambiguation rule so far, to have everything in place.
This will be maintained (by me) for at least 15 months. I don't expect to have a problem finding a successor.

**Comment by danielnaber** [comment]
Hi Jim, thanks, this looks like a very clean patch. When you say you'll be maintaining this for some time, does it mean you have funding? Can you estimate how much time you'll be able to spend working on it?

About the patch itself, we have problems with large binary files in git (issue #200) - do you think you could move the binary files to their own module (both in git and Maven) that is then fetched as a dependency? Maybe with some Java code to access the files, so that users who need a simple tagger but not LanguageTool would also benefit? If that works, we could use that approach for other languages, too. It is more important the more often the binary files are going to change.

**Comment by jimregan** [comment]
Not as clean as I would have liked, there are a few more changes to be made.

I have funding, though this is not part of my primary work. I'm not sure exactly how long I'll have to work on it, but there'll be a couple of days per month. On the other hand, I expect that some of my colleagues will be interested in adding rules, once the basics are in place, as it would tie in well with some of their projects.

I'll see what I can do with the binaries; in the meantime, I can redo the pull request without those pieces, and leave it open until it's solved.

Thanks for the quick answer!

**Comment by jimregan** [comment]
replacing with #387

**Pull request closed without merging**
