### PR TITLE
Adds a few new words to the English spelling.txt

### PR DESCRIPTION
**Pull request by SethiPandi**
Added a word to the English spelling.txt file:
* [areola](https://www.merriam-webster.com/dictionary/areola)

The rest are just taken from recently added words to Merriam-Webster:
* [iatrophobia](https://www.merriam-webster.com/dictionary/iatrophobia)
* [microtarget](https://www.merriam-webster.com/dictionary/microtarget)
* [nosocomephobia](https://www.merriam-webster.com/dictionary/nosocomephobia)
* [tomophobia](https://www.merriam-webster.com/dictionary/tomophobia)
* [zonkey](https://www.merriam-webster.com/dictionary/zonkey)
> \- Source: https://www.merriam-webster.com/words-at-play/new-words-in-the-dictionary

I grabbed a few, but then the website started having internal server errors; so I just left at it this. ^-^'

### CODE REVIEW

**Comment by danielnaber** [comment]
@MikeUnwalla Could you confirm and merge this PR?

**Comment by SethiPandi** [comment]
Added on more word I just used:
* [inutile](https://www.merriam-webster.com/dictionary/inutile)

I'll fix the merge conflicts now.

**Comment by MikeUnwalla** [comment]
@danielnaber , the suggestions from @SethiPandi are good, but before I merge, I have a question.

Inflections for nouns and verbs are missing from the PR. Also, derivate words are not in the PR. Some postags are in LT, some are not. What should I do?
* Merge the PR and deal with the missing inflections, derivatives, and POS later.
* Do not merge the PR and deal with all inflections, derivatives, and POS at one time.

**Comment by danielnaber** [comment]
@MikeUnwalla I'm fine with

> Merge the PR and deal with the missing inflections, derivatives, and POS later.

**Comment by SethiPandi** [comment]
I actually have a small question about that! Sorry!
I really wanted to do that myself, as my previous PRs were also closed and merged manually for similar reasons.

I don't see a contribution guide (CONTRIBUTING.md) in the repository. (The one in the README only really helps find good issues, but not any guidelines for the repository itself.)

By any chance could one be added that might explain in more detail the proper way to add new words and the different files that may need to be updated?

**Comment by MikeUnwalla** [comment]
@SethiPandi , some general comments (possibly, @danielnaber could improve and add them to a guide for contributors).

`spelling.txt` is for words that are used internationally. Merriam Webster is an American dictionary. Thus, as a minimum, it is useful to check also British English dictionaries. I like these:
* https://www.lexico.com/
* https://www.ldoceonline.com/
* https://www.collinsdictionary.com

For spelling that is applicable only to one locale, add the word to the applicable text file. For example, for an American spelling, add the word to `spelling_en-US.txt`.

To get a correct analysis of text, LanguageTool must know the part of speech (POS) that a word has. The word _zonkey_, for example, has no POS information:
image

You add `postags` in added.txt. For a list of postags, refer to `languagetool\resource\en\tagset.txt`.

**Pull request merged**
