### PR TITLE
Added rule id=SLIGHT_OF_HAND

### PR DESCRIPTION
**Pull request by MikeUnwalla**
By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
have the right to submit it under the open source license
indicated in the file; or

(b) The contribution is based upon previous work that, to the best
of my knowledge, is covered under an appropriate open source
license and I have the right under that license to submit that
work with modifications, whether created in whole or in part
by me, under the same open source license (unless I am
permitted to submit under a different license), as indicated
in the file; or

(c) The contribution was provided directly to me by some other
person who certified (a), (b) or (c) and I have not modified
it.

(d) I understand and agree that this project and the contribution
are public and that a record of the contribution (including all
personal information I submit with it, including my sign-off) is
maintained indefinitely and may be redistributed consistent with
this project or the open source license(s) involved.

Signed-off-by: Mike Unwalla <mike@techscribe.co.uk>

### CODE REVIEW

**Comment by PAX523** [comment]
Hi @MikeUnwalla ! Which file is missing?

**Comment by MikeUnwalla** [comment]
Hi @PAX523,
 
I added a rule to EN grammar.xml in my repository. Then, I created a pull request. I saw the change somewhere on https://github.com/MikeUnwalla/languagetool.

Because I am cautious and also not sure of the process, I asked Daniel to check (and implicitly, to merge that pull request), and he pointed out that my change to grammar.xml did not appear.

After I made the pull request, GitHub Desktop had a line from my repository to the languagetool master, but that line is not there now.

githubdesktop

(The.gitattributes file was added by GitHub when I set up the software. I don't know why it needs to be part of the pull request, but I cannot see how to prevent it.)

**Comment by jaumeortola** [comment]
Before you do a pull request or "sync", you need to "commit" the changes (with a message). If the message "X change(s)" is visible, I think the commit is pending.

**Comment by PAX523** [comment]
You have to consider following process:

1. You make any changes in your local workspace
2. You "commit" (consider the terminology) your changes into your local repository on your computer. This means, it isn't yet checked in into your remote repository. 
3. Now, you want to check in into your remote repository. You do this by "pushing" it. If you were successful then you should see your changes on github in your fork.
4. Start "pull request" on github. This associates your fork repository with the original repository and Daniel is able to merge your changes into his master.

Now, you already started a pull request. This means, the only thing that you have to do now, is to make sure that all your workspace changes are committed into your "local repository" and finally "pushed" to your remote repository.

Hope that helps.

Cheers

**Comment by MikeUnwalla** [comment]
Thanks @PAX523. 

@danielnaber, please review my pull request and merge if all is correct, (I know that I can do that, but for my first few commits, I prefer for someone with experience to do that to make sure that I have not done something stupid.)

**Comment by danielnaber** [comment]
Thanks, I've added the change. Your old test commits were part of the pull request, so I removed them manually (not sure how you could have avoided that).

**Pull request closed without merging**
