### PR TITLE
[fr] ignore English words

### PR DESCRIPTION
**Pull request by jaumeortola**
A local regression test is to be done before merging.

### CODE REVIEW

**Comment by LucieSteib** [comment]
Ah, cool! Excellent move, thanks @jaumeortola! 
If this pass; we should maybe include this commit to the weekly deploy, what do you think?

**Comment by jaumeortola** [comment]
> If this pass; we should maybe include this commit to the weekly deploy, what do you think?

No. We still need to create a new diff to be certain of the results. And it is better to start with OS only.

**Comment by LucieSteib** [comment]
Ah okay I though you might have done a local diff, I don't know why 🤦‍♀️ all good then, curious to see the results 😍

**Comment by GillouLT** [comment]
Just pushed changes deleting words that could be problematic as discussed in https://github.com/languagetooler-gmbh/languagetool-premium/issues/7080#issuecomment-2009547578

**Pull request merged**
