### PR TITLE
Grazie migration: Add pattern position to RuleMatch

### PR DESCRIPTION
**Pull request by Fatalll**
Add possibility to know rule pattern range.

### CODE REVIEW

**Comment by danielnaber** [comment]
Thanks, I understand this is the pattern position, i.e. unlike the usual position, which is just the position of the `<marker>`, isn't it? Could you describe the use case for it?

**Comment by Fatalll** [comment]
Well, we have 2 use cases:
1) We use rule pattern text as user exception mechanism because marker is too narrow for this.
ezgif-4-3f3551a22608
2) We use it to detect borders of unrelated parts of text. For exampe string literal with template:
`var result = "status is ${response.status}, data key is ${response.data.key}"`
Template will be deleted and text concatenated, and we can get false positives due to it.

**Comment by danielnaber** [comment]
I've merged the PR, thanks. For the second use case, have you considered using https://languagetool.org/development/api/org/languagetool/markup/AnnotatedText.html?

**Comment by Fatalll** [comment]
Oh, thanks for the tip! Not sure that it will solve all our problems in second case, but I will take a look :)

**Pull request merged**
