### PR TITLE
[fr] Adding athletes qualified for Olympics to ignore.txt

### PR DESCRIPTION
**Pull request by LucieSteib**
In the context of 
https://github.com/languagetooler-gmbh/languagetool-premium/issues/6682

Adding around 800 names to ignore.txt.
These are athletes qualified for the Olympics.

### CODE REVIEW

**Review by GillouLT — APPROVED** [review]
LGTM! :D

**Comment by Luisa-LT** [comment]
Stole it for German 🙏 ([commit](https://github.com/languagetool-org/languagetool/commit/f47a1cfc98cebfaec7ca1e8821982c15de8c8fff)) Big Merci @GillouLT!!

**Comment by GillouLT** [comment]
Well it's all thanks to Lucie !! :D

**Comment by Luisa-LT** [comment]
**Big Merci** to @LucieSteib then, too!! 🙏

**Pull request merged**
