### PR TITLE
Revert "[pt] More verbs/nouns fixes in disambiguation.xml"

### PR DESCRIPTION
**Pull request by marcoagpinto**
Reverts languagetool-org/languagetool#11104

Heya, @p-goulart ,

How did it break Premium?

Thanks!

## Summary by CodeRabbit

- **New Features**
	- Enhanced disambiguation rules for Portuguese language to improve verb identification, particularly for rare and contextually ambiguous cases.
  
- **Bug Fixes**
	- Removed a rule that incorrectly filtered rare verbs, ensuring better accuracy in verb identification. 
	- Modified existing rules to refine the handling of past participles in hyphenated words.

### CODE REVIEW

**Comment by p-goulart** [comment]
@marcoagpinto I don't know. I will not have the bandwidth to check this today.

**Comment by marcoagpinto** [comment]
@p-goulart 

Ahhhh... ok, it will be reverted and next week I will tag you again in this pull request.

Thanks!

**Comment by marcoagpinto** [comment]
Heya, @p-goulart ,

Do you now have the bandwidth to check what broke in Premium?

Thanks!

**Comment by marcoagpinto** [comment]
@jaumeortola 

Sorry to bother you, would you have some spare time to have a look at this issue?

Thanks!

**Comment by jaumeortola** [comment]
@marcoagpinto The issues in Premium are probably unrelated to Portuguese. There are many other things going on, and the DevOps team is taking care of that.

**Comment by marcoagpinto** [comment]
@jaumeortola 

Should I then repull the code and let it break Premium?

Thanks!

**Comment by jaumeortola** [comment]
Make a new PR, and we'll see what happens. I cannot see the failed test in the old PR.

**Pull request merged**
