### PR TITLE
[pt] Fix message for QUITES_P_BR

### PR DESCRIPTION
**Pull request by p-goulart**

### CODE REVIEW

**Comment by p-goulart** [comment]
All [test failures](https://app.circleci.com/pipelines/github/languagetool-org/languagetool/23612/workflows/d3b3eee3-71ae-4a34-9b37-128d6f312bff/jobs/23745/tests) are for CA and ES locales (@jaumeortola @tatigf20 fyi).

**Review by susanaboatto — APPROVED** [review]

**Comment by jaumeortola** [comment]
> All [test failures](https://app.circleci.com/pipelines/github/languagetool-org/languagetool/23612/workflows/d3b3eee3-71ae-4a34-9b37-128d6f312bff/jobs/23745/tests) are for CA and ES locales (@jaumeortola @tatigf20 fyi).

There was an error yesterday because the new entities files were missing. But that is solved now. Are there still errors? @p-goulart

**Comment by p-goulart** [comment]
Very odd, it doesn't trigger anything locally 🤷

**Comment by susanaboatto** [comment]
I am getting this error:

```
"C:\Program Files\Java\jdk1.8.0_301\bin\java.exe" "-javaagent:C:\Users\Susana\Documents\IntelliJ IDEA Community Edition 2022.1.3\lib\idea_rt.jar=52135:C:\Users\Susana\Documents\IntelliJ IDEA Community Edition 2022.1.3\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_301\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_301\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_301\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_301\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_301\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_301\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_301\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_301\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_301\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_301\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_301\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_301\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_301\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_301\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_301\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_301\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_301\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_301\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_301\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_301\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_301\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_301\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_301\jre\lib\rt.jar;C:\Users\Susana\languagetool\languagetool-language-modules\pt\target\test-classes;C:\Users\Susana\languagetool\languagetool-language-modules\pt\target\classes;C:\Users\Susana\languagetool\languagetool-core\target\classes;C:\Users\Susana\.m2\repository\com\carrotsearch\hppc\0.8.2\hppc-0.8.2.jar;C:\Users\Susana\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.14.2\jackson-databind-2.14.2.jar;C:\Users\Susana\.m2\repository\com\fasterxml\jackson\core\jackson-annotations\2.14.2\jackson-annotations-2.14.2.jar;C:\Users\Susana\.m2\repository\com\fasterxml\jackson\core\jackson-core\2.14.2\jackson-core-2.14.2.jar;C:\Users\Susana\.m2\repository\com\gitlab\dumonts\hunspell\2.1.1\hunspell-2.1.1.jar;C:\Users\Susana\.m2\repository\net\java\dev\jna\jna-platform\5.12.1\jna-platform-5.12.1.jar;C:\Users\Susana\.m2\repository\net\java\dev\jna\jna\5.12.1\jna-5.12.1.jar;C:\Users\Susana\.m2\repository\com\google\guava\guava\30.1-jre\guava-30.1-jre.jar;C:\Users\Susana\.m2\repository\com\google\guava\failureaccess\1.0.1\failureaccess-1.0.1.jar;C:\Users\Susana\.m2\repository\com\google\guava\listenablefuture\9999.0-empty-to-avoid-conflict-with-guava\listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar;C:\Users\Susana\.m2\repository\com\google\code\findbugs\jsr305\3.0.2\jsr305-3.0.2.jar;C:\Users\Susana\.m2\repository\org\checkerframework\checker-qual\3.5.0\checker-qual-3.5.0.jar;C:\Users\Susana\.m2\repository\com\google\errorprone\error_prone_annotations\2.3.4\error_prone_annotations-2.3.4.jar;C:\Users\Susana\.m2\repository\com\google\j2objc\j2objc-annotations\1.3\j2objc-annotations-1.3.jar;C:\Users\Susana\.m2\repository\com\hankcs\aho-corasick-double-array-trie\1.2.2\aho-corasick-double-array-trie-1.2.2.jar;C:\Users\Susana\.m2\repository\com\optimaize\languagedetector\language-detector\0.6\language-detector-0.6.jar;C:\Users\Susana\.m2\repository\net\arnx\jsonic\1.2.11\jsonic-1.2.11.jar;C:\Users\Susana\.m2\repository\com\intellij\annotations\12.0\annotations-12.0.jar;C:\Users\Susana\.m2\repository\com\vdurmont\emoji-java\5.1.1\emoji-java-5.1.1.jar;C:\Users\Susana\.m2\repository\commons-logging\commons-logging\1.2\commons-logging-1.2.jar;C:\Users\Susana\.m2\repository\commons-validator\commons-validator\1.7\commons-validator-1.7.jar;C:\Users\Susana\.m2\repository\commons-digester\commons-digester\2.1\commons-digester-2.1.jar;C:\Users\Susana\.m2\repository\io\github\resilience4j\resilience4j-circuitbreaker\1.7.1\resilience4j-circuitbreaker-1.7.1.jar;C:\Users\Susana\.m2\repository\io\vavr\vavr\0.10.2\vavr-0.10.2.jar;C:\Users\Susana\.m2\repository\io\vavr\vavr-match\0.10.2\vavr-match-0.10.2.jar;C:\Users\Susana\.m2\repository\io\github\resilience4j\resilience4j-core\1.7.1\resilience4j-core-1.7.1.jar;C:\Users\Susana\.m2\repository\io\github\resilience4j\resilience4j-micrometer\1.7.1\resilience4j-micrometer-1.7.1.jar;C:\Users\Susana\.m2\repository\io\grpc\grpc-netty-shaded\1.50.2\grpc-netty-shaded-1.50.2.jar;C:\Users\Susana\.m2\repository\io\perfmark\perfmark-api\0.25.0\perfmark-api-0.25.0.jar;C:\Users\Susana\.m2\repository\io\grpc\grpc-core\1.50.2\grpc-core-1.50.2.jar;C:\Users\Susana\.m2\repository\com\google\code\gson\gson\2.9.0\gson-2.9.0.jar;C:\Users\Susana\.m2\repository\com\google\android\annotations\4.1.1.4\annotations-4.1.1.4.jar;C:\Users\Susana\.m2\repository\io\grpc\grpc-protobuf\1.50.2\grpc-protobuf-1.50.2.jar;C:\Users\Susana\.m2\repository\io\grpc\grpc-api\1.50.2\grpc-api-1.50.2.jar;C:\Users\Susana\.m2\repository\io\grpc\grpc-context\1.50.2\grpc-context-1.50.2.jar;C:\Users\Susana\.m2\repository\com\google\protobuf\protobuf-java\3.21.7\protobuf-java-3.21.7.jar;C:\Users\Susana\.m2\repository\com\google\api\grpc\proto-google-common-protos\2.9.0\proto-google-common-protos-2.9.0.jar;C:\Users\Susana\.m2\repository\io\grpc\grpc-protobuf-lite\1.50.2\grpc-protobuf-lite-1.50.2.jar;C:\Users\Susana\.m2\repository\io\grpc\grpc-stub\1.50.2\grpc-stub-1.50.2.jar;C:\Users\Susana\.m2\repository\io\micrometer\micrometer-registry-prometheus\1.7.1\micrometer-registry-prometheus-1.7.1.jar;C:\Users\Susana\.m2\repository\io\micrometer\micrometer-core\1.7.1\micrometer-core-1.7.1.jar;C:\Users\Susana\.m2\repository\org\hdrhistogram\HdrHistogram\2.1.12\HdrHistogram-2.1.12.jar;C:\Users\Susana\.m2\repository\org\latencyutils\LatencyUtils\2.0.3\LatencyUtils-2.0.3.jar;C:\Users\Susana\.m2\repository\io\prometheus\simpleclient_common\0.10.0\simpleclient_common-0.10.0.jar;C:\Users\Susana\.m2\repository\io\prometheus\simpleclient\0.12.0\simpleclient-0.12.0.jar;C:\Users\Susana\.m2\repository\io\prometheus\simpleclient_tracer_otel\0.12.0\simpleclient_tracer_otel-0.12.0.jar;C:\Users\Susana\.m2\repository\io\prometheus\simpleclient_tracer_common\0.12.0\simpleclient_tracer_common-0.12.0.jar;C:\Users\Susana\.m2\repository\io\prometheus\simpleclient_tracer_otel_agent\0.12.0\simpleclient_tracer_otel_agent-0.12.0.jar;C:\Users\Susana\.m2\repository\io\prometheus\simpleclient_guava\0.12.0\simpleclient_guava-0.12.0.jar;C:\Users\Susana\.m2\repository\javax\activation\javax.activation-api\1.2.0\javax.activation-api-1.2.0.jar;C:\Users\Susana\.m2\repository\javax\annotation\javax.annotation-api\1.3.2\javax.annotation-api-1.3.2.jar;C:\Users\Susana\.m2\repository\javax\measure\unit-api\1.0\unit-api-1.0.jar;C:\Users\Susana\.m2\repository\javax\xml\bind\jaxb-api\2.3.0\jaxb-api-2.3.0.jar;C:\Users\Susana\.m2\repository\net\loomchild\segment\2.0.1\segment-2.0.1.jar;C:\Users\Susana\.m2\repository\org\apache\commons\commons-lang3\3.12.0\commons-lang3-3.12.0.jar;C:\Users\Susana\.m2\repository\org\apache\commons\commons-pool2\2.11.1\commons-pool2-2.11.1.jar;C:\Users\Susana\.m2\repository\org\apache\commons\commons-text\1.10.0\commons-text-1.10.0.jar;C:\Users\Susana\.m2\repository\org\apache\lucene\lucene-backward-codecs\5.5.5\lucene-backward-codecs-5.5.5.jar;C:\Users\Susana\.m2\repository\org\apache\lucene\lucene-core\5.5.5\lucene-core-5.5.5.jar;C:\Users\Susana\.m2\repository\org\carrot2\morfologik-fsa\2.1.9\morfologik-fsa-2.1.9.jar;C:\Users\Susana\.m2\repository\org\carrot2\morfologik-fsa-builders\2.1.9\morfologik-fsa-builders-2.1.9.jar;C:\Users\Susana\.m2\repository\org\carrot2\morfologik-speller\2.1.9\morfologik-speller-2.1.9.jar;C:\Users\Susana\.m2\repository\org\carrot2\morfologik-stemming\2.1.9\morfologik-stemming-2.1.9.jar;C:\Users\Susana\.m2\repository\org\glassfish\jaxb\jaxb-runtime\2.3.0\jaxb-runtime-2.3.0.jar;C:\Users\Susana\.m2\repository\org\glassfish\jaxb\jaxb-core\2.3.0\jaxb-core-2.3.0.jar;C:\Users\Susana\.m2\repository\org\glassfish\jaxb\txw2\2.3.0\txw2-2.3.0.jar;C:\Users\Susana\.m2\repository\com\sun\istack\istack-commons-runtime\3.0.5\istack-commons-runtime-3.0.5.jar;C:\Users\Susana\.m2\repository\org\jvnet\staxex\stax-ex\1.7.8\stax-ex-1.7.8.jar;C:\Users\Susana\.m2\repository\com\sun\xml\fastinfoset\FastInfoset\1.2.13\FastInfoset-1.2.13.jar;C:\Users\Susana\.m2\repository\org\jetbrains\annotations\20.1.0\annotations-20.1.0.jar;C:\Users\Susana\.m2\repository\org\jetbrains\intellij\deps\trove4j\1.0.20200330\trove4j-1.0.20200330.jar;C:\Users\Susana\.m2\repository\org\json\json\20220924\json-20220924.jar;C:\Users\Susana\.m2\repository\org\slf4j\slf4j-api\2.0.7\slf4j-api-2.0.7.jar;C:\Users\Susana\.m2\repository\tech\units\indriya\1.3\indriya-1.3.jar;C:\Users\Susana\.m2\repository\tech\uom\lib\uom-lib-common\1.1\uom-lib-common-1.1.jar;C:\Users\Susana\.m2\repository\org\languagetool\portuguese-pos-dict\0.3\portuguese-pos-dict-0.3.jar;C:\Users\Susana\.m2\repository\junit\junit\4.13.2\junit-4.13.2.jar;C:\Users\Susana\.m2\repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar;C:\Users\Susana\languagetool\languagetool-core\target\test-classes" org.languagetool.rules.pt.PortuguesePatternRuleTest
Running XML pattern tests...
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
LanguageTool version 6.3-SNAPSHOT (null, null)
Known languages: [Portuguese, Portuguese (Portugal), Portuguese (Brazil), Portuguese (Angola preAO), Portuguese (Moçambique preAO), Testlanguage]
Running XML validation for pt/grammar.xml...
Exception in thread "main" java.io.IOException: Cannot load or parse '/org/languagetool/rules/pt/grammar.xml'
	at org.languagetool.XMLValidator.validateWithXmlSchema(XMLValidator.java:117)
	at org.languagetool.rules.patterns.PatternRuleTest.validatePatternFile(PatternRuleTest.java:242)
	at org.languagetool.rules.patterns.PatternRuleTest.validatePatternFile(PatternRuleTest.java:218)
	at org.languagetool.rules.patterns.PatternRuleTest.runTestForLanguage(PatternRuleTest.java:189)
	at org.languagetool.rules.patterns.PatternRuleTest.runGrammarRulesFromXmlTestIgnoringLanguages(PatternRuleTest.java:184)
	at org.languagetool.rules.patterns.PatternRuleTest.main(PatternRuleTest.java:924)
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/Susana/languagetool/languagetool-language-modules/pt/target/classes/org/languagetool/resource/pt/entities/messages.ent
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at org.languagetool.XMLValidator$EntityAsInput.setInputStream(XMLValidator.java:301)
	at org.languagetool.XMLValidator$EntityAsInput.<init>(XMLValidator.java:387)
	at org.languagetool.XMLValidator$LSRuleEntityResolver.resolveResource(XMLValidator.java:242)
	at com.sun.org.apache.xerces.internal.util.DOMEntityResolverWrapper.resolveEntity(DOMEntityResolverWrapper.java:118)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.resolveEntityAsPerStax(XMLEntityManager.java:995)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startEntity(XMLEntityManager.java:1210)
	at com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.startPE(XMLDTDScannerImpl.java:739)
	at com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.skipSeparator(XMLDTDScannerImpl.java:2108)
	at com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.scanDecls(XMLDTDScannerImpl.java:2071)
	at com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.scanDTDInternalSubset(XMLDTDScannerImpl.java:363)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.dispatch(XMLDocumentScannerImpl.java:1128)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.next(XMLDocumentScannerImpl.java:1073)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:948)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:113)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:507)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:867)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:796)
	at com.sun.org.apache.xerces.internal.jaxp.validation.StreamValidatorHelper.validate(StreamValidatorHelper.java:152)
	at com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorImpl.validate(ValidatorImpl.java:116)
	at javax.xml.validation.Validator.validate(Validator.java:124)
	at org.languagetool.XMLValidator.validateInternal(XMLValidator.java:218)
	at org.languagetool.XMLValidator.validateWithXmlSchema(XMLValidator.java:115)
	... 5 more

Process finished with exit code 1
```

**Pull request merged**
