### PR TITLE
updated tags file location

### PR DESCRIPTION
**Pull request by gatitoneku**
Attempted fix for #746, write in in the same directory as the .dict file instead of temp

### CODE REVIEW

**Comment by danielnaber** [comment]
Thanks. I think there should be a slightly cleaner way that works without `substring`, maybe `File.getParent()`?

**Comment by danielnaber** [comment]
I assume you've not just changed the code but also testes manually that it works, haven't you? In that case I'd merge your change without testing it myself.

**Comment by gatitoneku** [comment]
Yeah, i've tested running SynthDictionaryBuilder and it generated the tag file in the same location as the dict file.

**Comment by danielnaber** [comment]
Thanks, I've merged your change now.

**Comment by gatitoneku** [comment]
Oops i forgot to delete() the directory after usage.  Should i make a PR again?

**Comment by danielnaber** [comment]
> Oops i forgot to delete() the directory after usage. Should i make a PR again?

Sorry, I'm not familiar with the flow now - which directory? There's no reason to delete the result, I guess? :-)

**Comment by gatitoneku** [comment]
I used ```File outputDirectory = new File(outputFilename).getParentFile();``` to get the directory of the output files. What i meant was I forgot to delete the ```File``` object.

**Pull request merged**
