### PR TITLE
[pt] added picky to various style rules

### PR DESCRIPTION
**Pull request by maphjo**

### CODE REVIEW

**Comment by marcoagpinto** [comment]
Hello!

Could you commit the changes?

I am scared of clicking on the button since I am unable to understand what is in the code, or what it will change with it.

**Comment by marcoagpinto** [comment]
ahhhh... never mind, let me click.

**Comment by maphjo** [comment]
@marcoagpinto Thank you! I would have merged it myself in a minute. ;-)
You can see the changes when you click on "Commits" and then the commit number. Or on "Files changed".

**Comment by marcoagpinto** [comment]
ahhhhhhhhh ❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Pull request merged**
