### PR TITLE
[en] basic errors not found: NNS + VBZ #4275

### PR DESCRIPTION
**Pull request by AzadehSafakish**
Draft version that handles the aforementioned errors with practically no false-positives.

I had trouble adding on to the previous rules for subject-verb agreement, so I made my own rule group. It's only good for some very specific contexts though, so I want to expand it and clean it up.

Attaching the grepped .txt that I used in the source checker... never mind it's too big :/
But I grepped for plural determiners (some, all, these, etc) and poss. pronouns.

I'll try to have this handled by Friday.
#4275

### CODE REVIEW

**Comment by udomai** [comment]
Nice! You're tackling another biggie. Being FP-free sounds wonderful :)

**Comment by AzadehSafakish** [comment]
Well, the patterns still apply to very specific contexts, which is the only way to get it FP-free. 

However, they do correct the errors that they need to, as well as several other sentences. 

No FPs that I can find in the rule editor or the first 1,000,000 sentences in the source checker (grepped for 'all|many|some|the|these|those|my|your|his|her|its|our|their').

**Comment by udomai** [comment]
mergeable → category

**Comment by AzadehSafakish** [comment]
moved to grammar

**Comment by udomai** [comment]
Merged manually: 41b8335b1ec0122f4c169d296061526efce594ba

**Pull request closed without merging**
