### PR TITLE
[ru] pymorph pos tag generator script

### PR DESCRIPTION
**Pull request by kostyfisik**

### CODE REVIEW

**Comment by yakovru** [comment]
@kostyfisik, how use this script?
I need install enchat python3 module? 
What is needed?

**Comment by yakovru** [comment]
What is file "all_tags.txt", "need-tag.txt" "unique-tag.txt" "final-tags-pymorph.txt" ?

final-tags-pymorph.txt is result
need-tag.txt is input, it is correct?

**Comment by kostyfisik** [comment]
I added the instruction to the scipt. Enchant is not actually needed, I removed that import.

**Comment by yakovru** [comment]
Thanks!

**Pull request merged**
