### PR TITLE
[be] Update Belarusian spell dictionary

### PR DESCRIPTION
**Pull request by alex73**
Dictionary contains updated set of Belarusian words

### CODE REVIEW

**Comment by danielnaber** [comment]
What do you think of publishing the binary dict as a separate Maven artifact that LT uses as an external dependency? This way, we'd avoid putting more binary data into the LT main repo.

**Comment by alex73** [comment]
Well, I can do it, of course. Could you please to point me the same exist external dependency ? I'm not sure that I have enough knowledge of languagetool internals to do it myself.

**Comment by alex73** [comment]
@danielnaber So, is it some other language dict that was moved to external dependency ? I would like to use it as example.

**Comment by danielnaber** [comment]
@alex73 `org.languagetool:portuguese-pos-dict` ([source](https://github.com/languagetool-org/portuguese-pos-dict)) has recently been moved to its own package

**Comment by alex73** [comment]
@danielnaber Belarusian dictionary created from https://github.com/Belarus/GrammarDB. Can I don't create https://github.com/languagetool-org/belarusian-pos-dict, but add code for build dictionary to https://github.com/Belarus/GrammarDB and publish artifact with hunspell dictionary to Maven Central ?

**Comment by danielnaber** [comment]
@alex73 Yes, it doesn't matter where the repo is hosted on github, as long as it's published on Maven Central.

**Comment by alex73** [comment]
@danielnaber I added dictionary as dependency, and looks like languagetool-language-modules/be works good. But "LanguageTool stand-alone GUI" test was failed.

**Comment by danielnaber** [comment]
@alex73 I'm sorry, I won't have time to debug that. I suggest you run the affected test in an IDE with a debugger to see what's wrong.

**Comment by alex73** [comment]
@danielnaber I fixed it. Looks like it can be merged to master.
The issue was: when I removed spelling.txt, then "LanguageTool stand-alone GUI" was failed with strange error: https://app.circleci.com/pipelines/github/languagetool-org/languagetool/28091/workflows/367758ac-2a51-4031-aeae-6a8a2258c552/jobs/28247

**Comment by danielnaber** [comment]
Have you also moved `ignore.txt` to the external dependency? It should stay in LT, so it can be changed without updating the external dependency.

**Comment by alex73** [comment]
@danielnaber Yes, I was moved it into external project. Just returned to LT.

**Comment by jaumeortola** [comment]
This looks good to me. 
For other languages, the version number is in the main [pom.xml](https://github.com/languagetool-org/languagetool/blob/20ad4166990071c8c6f97527bcc599633ec8bc98/pom.xml#L215) file. 
Should we do the same for Belarusian?

**Comment by alex73** [comment]
@jaumeortola I moved version number to the /pom.xml

**Review by jaumeortola — APPROVED** [review]

**Pull request merged**
