### PR TITLE
[pt-PT] Rewrote rule ID:DO_QUE_AQUELE_QUE_ÀQUELE_QUE_PT_PT

### PR DESCRIPTION
**Pull request by marcoagpinto**
Heya,

Another pt-PT rule rewritten and thus a lot smaller/simpler than the previous code.

### CODE REVIEW

**Comment by marcoagpinto** [comment]
Ahhhhh...

@p-goulart 

```
Title: <plaintext>
1.) Line 1, column 62, Rule ID: DO_QUE_AQUELE_QUE_ÀQUELE_QUE_PT_PT[1] [temp_off]
Message: Para conferir mais clareza ao seu texto, busque usar uma linguagem mais concisa.
Suggestion: àquela
Rule source: /org/languagetool/rules/pt/pt-PT/style.xml
A parte de um iceberg que está debaixo da água é muito maior do que aquela que está acima da água.
                                                             ^^^^^^^^^^^^^                        

Title: <plaintext>
1.) Line 1, column 38, Rule ID: DO_QUE_AQUELE_QUE_ÀQUELE_QUE_PT_PT[1] [temp_off]
Message: Para conferir mais clareza ao seu texto, busque usar uma linguagem mais concisa.
Suggestion: àquele
Rule source: /org/languagetool/rules/pt/pt-PT/style.xml
Este vinho tem um aroma mais frutado do que aquele que experimentamos antes.
                                     ^^^^^^^^^^^^^                          

Title: <plaintext>
1.) Line 1, column 172, Rule ID: DO_QUE_AQUELE_QUE_ÀQUELE_QUE_PT_PT[1] [temp_off]
Message: Para conferir mais clareza ao seu texto, busque usar uma linguagem mais concisa.
Suggestion: àquelas
Rule source: /org/languagetool/rules/pt/pt-PT/style.xml
...ões observadas recentemente em descargas que simulam raios, as quais são significativamente maiores do que aquelas que poderiam ser produzidas pelas temperaturas observadas.
                                                                                                       ^^^^^^^^^^^^^^                                                           

Title: <plaintext>
1.) Line 1, column 158, Rule ID: DO_QUE_AQUELE_QUE_ÀQUELE_QUE_PT_PT[1] [temp_off]
Message: Para conferir mais clareza ao seu texto, busque usar uma linguagem mais concisa.
Suggestion: àquelas
Rule source: /org/languagetool/rules/pt/pt-PT/style.xml
...osamente, e que também carregavam genes ligados à ELA, desenvolveram a doença em idades mais jovens do que aquelas que eram sedentárias.
                                                                                                       ^^^^^^^^^^^^^^                      
Portuguese (Portugal): 4 total matches
Portuguese (Portugal): 811129 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
Portuguese (Portugal): 54420 input lines ignored (e.g. not between 10 and 300 chars or at least 4 tokens)
```

**Comment by p-goulart** [comment]
Um, those are all instances of 'do que', yes. Is there a single instance of 'melhor a' in the corpus?

**Comment by marcoagpinto** [comment]
> Um, those are all instances of 'do que', yes. Is there a single instance of 'melhor a' any the corpus?

"melhor a"?

**Comment by marcoagpinto** [comment]
Ahhhhhhh… you want to create a rule also with “melhor a” instead of “do que”?

**Comment by marcoagpinto** [comment]
@p-goulart 
https://dicionario.priberam.org/%C3%A0quela
“a aquela”
“é melhor a aquela que tínhamos”
?

Pedro, try this second sentence in the Editor, and it will suggest using the contraction “àquela” 😛 😛 😛 😛 

To me it sounds well in pt-PT.

**Comment by p-goulart** [comment]
... Marco, with all due to respect, I understand how to form contractions in my own language. My question has absolutely nothing to do with the contraction, and neither does this rule. This is a rule that replaces `do que aquel[ea]s?` with `àquel[ea]s?`, and this does not seem right to me.

Can you point us to a single source stating that it is _prescriptively_ correct to form comparatives with 'a' instead of '[do] que'? Because **that** is the actual transformation that this rule proposes.

**Comment by marcoagpinto** [comment]
@p-goulart 

I don't know any more, so I went to ChatGPT:


Screenshot 2024-01-02 at 13-43-51 ChatGPT


Maybe it is better to delete the rule?

**Comment by marcoagpinto** [comment]
It takes me just a few seconds to delete it if required 😛 😛 😛 😛

**Comment by p-goulart** [comment]
If you yourself can't justify this rule for `pt-PT`, then it sounds like it should be disabled.

**Comment by marcoagpinto** [comment]
I have just deleted it.

I will press "merge" after the checks!

**Comment by marcoagpinto** [comment]
I want LanguageTool to be perfect, so in doubt, it is better to play safe always.

**Comment by p-goulart** [comment]
I still don't understand what this rule was meant to be doing. Is it _descriptively_ grammatical to use 'a' instead of 'do que' in Portugal?

**Comment by marcoagpinto** [comment]
> I still don't understand what this rule was meant to be doing. Is it _descriptively_ grammatical to use 'a' instead of 'do que' in Portugal?

Well, it was a rule to reduce the number of words in a sentence, to simplify the writing, but it is now deleted.

**Comment by p-goulart** [comment]
There does come a point, though, when striving for conciseness becomes detrimental to clarity. There are many such rules in Portuguese – using fewer words is not always the same as being 'clearer'.

If text cannot be simplified without sacrificing transparency (or, worse, as in this case, correctness), then it probably shouldn't be simplified at all. At times, allowing text to flow _naturally_ may be much more beneficial to our users (and their readers).

---

Maybe next time, before you dedicate your time to optimising a rule, have a look at what the rule actually *does* and see if its effects are *grammatical*, both in the descriptive **and** the prescriptive senses.

It is not the first time that I see a `pt-PT` rule with very questionable grammar, but I mostly just chalk it up to `pt-PT` being largely alien to me and trust that you understand what's going on. I only pushed back on this one because it sounded _very_ ungrammatical, but I don't double-check all `pt-PT` rules.

**Pull request merged**
