### PR TITLE
re:pr#940 | added pretty exceptions handling

### PR DESCRIPTION
**Pull request by oserikov**
Just figured out that there can be uninformative exceptions. Added some handling.

### CODE REVIEW

**Comment by danielnaber** [comment]
I think it would be better to keep the original exception like this: `RuntimeException("Unexpected reference to capturing group.", e)`. Could you also give an example of what it looks before and after this change?

**Comment by oserikov** [comment]
@danielnaber OK, will improve this PR today after 20:00 gmt.

**Comment by oserikov** [comment]
Improved the exception message a little.

The cause of that PR is the personal experience -- while testing the potential fix of an issue I've copy-pasted some rules from the different languages rules sets to cover the fix and received the following stacktrace on the mvn test:
```<!-- language: lang-none -->
[ERROR] Tests run: 8, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.742 s <<< FAILURE! - in org.languagetool.rules.patterns.DemoPatternRuleTest
[ERROR] testRules(org.languagetool.rules.patterns.DemoPatternRuleTest)  Time elapsed: 0.244 s  <<< ERROR!
java.lang.IndexOutOfBoundsException: No group 4
        at java.util.regex.Matcher.group(Matcher.java:538)
        at org.languagetool.rules.patterns.RegexPatternRule.processMessage(RegexPatternRule.java:133)
        ...
```
It was hard to determine whether I've made a mistake in one of the rules or there were a problem in the code. This PR version will raise more informative exception:
```<!-- language: lang-none -->
[ERROR] Tests run: 8, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.652 s <<< FAILURE! - in org.languagetool.rules.patterns.DemoPatternRuleTest
[ERROR] testRules(org.languagetool.rules.patterns.DemoPatternRuleTest)  Time elapsed: 0.215 s  <<< ERROR!
java.lang.RuntimeException: Unexpected reference to capturing group in rule with id REGEX_PATTERN_RULE_DEMO_BAD_CAPTURING_GROUP_0[1].
        at org.languagetool.rules.patterns.RegexPatternRule.match(RegexPatternRule.java:96)
        at org.languagetool.rules.patterns.PatternRuleTest.getMatches(PatternRuleTest.java:600)
        ...
Caused by: java.lang.IndexOutOfBoundsException: No group 4
        at java.util.regex.Matcher.group(Matcher.java:538)
        at org.languagetool.rules.patterns.RegexPatternRule.processMessage(RegexPatternRule.java:142)
        ...
```
To reproduce both exceptions posted there one has to add e.g. this rule to the test language `grammar.xml` (org/languagetool/rules/xx/grammar.xml):
```xml
<rule id="REGEX_PATTERN_RULE_DEMO_BAD_CAPTURING_GROUP_0" name="see: RegexpPatternRuleTest">
    <regexp>(fo.) (bar)</regexp>
    <message>msg: <suggestion>suggestion \4</suggestion></message>
    <example correction="suggestion bar"><marker>fou bar</marker></example>
</rule>
```

**Comment by danielnaber** [comment]
Thanks, I've merged your PR. I've removed the use of final static Strings, as they were only used one, so it's often better to have the string directly in the place where it's used.

**Pull request merged**
