### PR TITLE
[pt] Added AP to rule ID:A_WORD

### PR DESCRIPTION
**Pull request by marcoagpinto**
Heya,

An antipattern to remove false positives.

### CODE REVIEW

**Comment by p-goulart** [comment]
Since this PR involves entities, let's wait for #8974 just to keep things clean.

**Review by p-goulart — APPROVED** [review]

**Comment by marcoagpinto** [comment]
Pedro, is it now that one presses the "Merge Pull Request"?

Thanks!

**Comment by p-goulart** [comment]
It's good practice to wait for the checks to pass:

Screenshot 2023-07-19 at 12 26 11 PM

**Comment by marcoagpinto** [comment]
ahhhh... sorry... 😛

**Pull request merged**
