### PR TITLE
speed up XmlRuleDisambiguator

### PR DESCRIPTION
**Pull request by donnerpeter**
don't even run rules that can't possibly match, judging by their token strings/regexps

to determine that, parse simple yet most frequent regexps that have just |?[] in them, extract all possible values from them
and use that set for faster PatternToken.isStringTokenMatched and to build index of rules by word form in XmlRuleDisambiguator

### CODE REVIEW

**Comment by donnerpeter** [comment]
For me, this speeds up the `testGrammarRulesFromXML` part of `EnglishPatternRuleTest.testRules` by about 40%.

**Comment by danielnaber** [comment]
Peter, I can confirm the speed-up, this is great! I'd suggest moving calcFormHints etc. to its own class. Could you also write some tests for it and add a comment about how the actual optimization in `disambiguate` works?

**Comment by donnerpeter** [comment]
`calcFormHints` is pretty coupled with `PatternToken` internals. What would you imagine the responsibility of that new class to be? Or did you mean just `getPossibleRegexpValues` which is easy to extract to some utility and write tests about?

As a comment, would this be enough?
     /**
   * @return rules that have a chance to be triggered by the given sentence, e.g. the ones that match against tokens
   * present there, or with too general regular expressions.
   */

**Comment by danielnaber** [comment]
> Or did you mean just getPossibleRegexpValues which is easy to extract to some utility and write tests about?

Yes, I care mostly about the tests.

**Comment by jaumeortola** [comment]
In languages with a large disambiguation file the speed-up is very noticeable. Thank you! 

Could this approach be used with the grammar files?

**Comment by donnerpeter** [comment]
@danielnaber Would a couple of tests in `PatternTokenTest` without class extraction be OK as well?

@jaumeortola You're welcome! I believe `simpleRuleTokens`/`inflectedRuleTokens` already serve a similar purpose with grammar rules, but enhancements from regex parsing might also benefit the performance. Any idea of a test that runs a lot of rules on a lot of sentences, where the effects could be noticeable?

**Comment by danielnaber** [comment]
@donnerpeter Yes, just a test would be fine.

**Comment by danielnaber** [comment]
I've created an issue at https://github.com/languagetool-org/languagetool/issues/3744 with an idea on how we can maybe improve performance for regex also for the pattern rules.

**Pull request merged**
