### PR TITLE
[en] improve SEVERAL_OTHER

### PR DESCRIPTION
**Pull request by tiff**
For https://github.com/languagetool-org/languagetool/issues/1694

@MikeUnwalla please let me know if this is good.

### CODE REVIEW

**Comment by MikeUnwalla** [comment]
@tiff, You can optimize the 'or' and use `<token postag_regexp="yes" postag="SENT_END|VBD?"/>`

But, adding the VB/VBD postags causes many false positives for noun clusters. Use https://community.languagetool.org/ruleEditor/expert?devMode=true&factor=10 to see what I mean.

**Comment by tiff** [comment]
@MikeUnwalla thanks for the feedback. See my recent changes. No more false positives are created.

**Comment by MikeUnwalla** [comment]
@tiff , I don't understand this Git message:

```
Pull request successfully merged and closed
You’re all set—the fix-1694 branch can be safely deleted.
```
I will let you deal with it!

**Comment by tiff** [comment]
It means you can safely delete a git branch after it got merged. I just did that. Thanks for looking into it.

**Pull request merged**
