### PR TITLE
[de] added words that shouldn't be accepted by the speller

### PR DESCRIPTION
**Pull request by Luisa-LT**
Interesting info: Almost all are corrected by `gGEC` but since not all users get gGEC matches yet, I added them to `prohibit.txt`

### CODE REVIEW

**Review by AgnesKleinhans — APPROVED** [review]
cool!! 🚀

**Comment by danielnaber** [comment]
The PR is okay, but we should fix the underlying issue here, as e.g. "Bauerbrot" doesn't seem to be a special case. "Bauerwitwe" is also accepted, for example.

**Comment by danielnaber** [comment]
> Where could I add e.g. Bauer that it is not used as a compound part?

Not sure I understand the question, but currently it's in `words_no_infix_s.txt` and it just doesn't seem to belong there, as the typical compound part is `Bauern...`

**Comment by Luisa-LT** [comment]
Of course, true it needs to have an -n, I'll add it there

**Comment by Luisa-LT** [comment]
https://github.com/languagetool-org/languagetool/pull/9680/commits/468e042123d2d925c970adb19beaa38bbbd747f9

**Pull request merged**
