### PR TITLE
[pt] Rewrote rule ID:DIFERENTES

### PR DESCRIPTION
**Pull request by marcoagpinto**
Heya,

I have rewritten another rule.

```
Portuguese (Portugal): 35 total matches
Portuguese (Portugal): 811110 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```

[6.txt](https://github.com/languagetool-org/languagetool/files/13246778/6.txt)

### CODE REVIEW

**Review by susanaboatto — APPROVED** [review]

**Comment by marcoagpinto** [comment]
@susanaboatto 

HELP!!!!

It says it has conflicts!

**Comment by marcoagpinto** [comment]
Ahhhh... it doesn't matter, I will recommit with a more recent style.xml

**Comment by susanaboatto** [comment]
I have merged the changes in master into this branch.

**Comment by marcoagpinto** [comment]
ahhh… let us see if the conflicts are gone in the check.

😛

**Pull request closed without merging**
