### PR TITLE
[ru] Added 'темпе' to Russian dictionary

### LINKED ISSUE #8900: [ru] unknown темпе food
false positive in `Темпе производится из целых соевых бобов`
https://ru.wikipedia.org/wiki/Темпе

### PR DESCRIPTION
**Pull request by juzyz**
Fix for issue: [ru] unknown темпе food #8900.
Close #8900

### CODE REVIEW

**Comment by juzyz** [comment]
Please merge this pull request.

**Comment by juzyz** [comment]
@GillouLT 
@danielnaber 

I'm a new contributor and I would like to ask you to check my pull request and approve it if it is everything ok.

**Comment by danielnaber** [comment]
@yakovru Could you check this PR?

**Comment by juzyz** [comment]
@GillouLT
@danielnaber
@yakovru

Just a friendly follow-up on my pull request. I understand everyone's busy, but I'm eager to contribute and would appreciate your review whenever you get a chance. Let me know if there's anything I can do to assist in the process.

Thanks again!

**Pull request merged**
