### PR TITLE
[en] DRAFT God with a capital 'G'

### PR DESCRIPTION
**Pull request by AzadehSafakish**
Not finished removing all the FPs yet, but I'm pushing it as a draft.

image

Oh my God
Thank God

Etc...

### CODE REVIEW

**Comment by AzadehSafakish** [comment]
Closing for now

**Comment by udomai** [comment]
Comment: I've done some additional googling. So, basically, "God" is capitalized when it's a NNP, and refers to the abrahamic god. It's lowercase when a common noun ("the Greek god of war"). So far, so good.
But there's more: In expressions like TGIF, the speaker is typically not having a religious thought, but quite a profane one. When there's no real religious background, even "the" god is spelled in lowercase.
Capitalizing it would make such utterances as "OMG", "Thank god", etc. about religion. My guess is, prescribing this would not sit well with quite a few users (personally, I'd deactivate the rule)… so, shelving this draft is probably best.

**Comment by danielnaber** [comment]
blender

**Comment by udomai** [comment]
nice detail in the alternative text

image

**Pull request closed without merging**
