### PR TITLE
String rework

### PR DESCRIPTION
**Pull request by comradekingu**
I don't know about "whitespace" vs "space", nor what the policy on full stops is.

### CODE REVIEW

**Comment by danielnaber** [comment]
Thanks, but I hesitate to make these small changes to the English text, as it triggers a re-wording of all translations. Could you maybe provide a pull requests that only fixes real errors and skips the small stuff (like uppercase and typography)?

**Comment by comradekingu** [comment]
@danielnaber No translator has ever complained about that. And there is a good chance translations will improve as a result. Weblate fortunately handles "fuzzy" strings correctly, so translations are just marked fuzzy for review, nothing else happens.

**Comment by danielnaber** [comment]
We're not using Weblate but transifex. It might *mark* them as fuzzy, but via the API we'll get the English string again until the translation has been updated.

**Comment by comradekingu** [comment]
@danielnaber https://hosted.weblate.org/projects/languagetool am i missing something?
Yes, Transifex handles fuzzy strings so badly it takes time to get into.

**Comment by danielnaber** [comment]
https://hosted.weblate.org/projects/languagetool is not in use

**Comment by comradekingu** [comment]
@danielnaber Was there an issue with this?

**Pull request closed without merging**
