### PR TITLE
Update EnglishWordRepeatRule.java

### PR DESCRIPTION
**Pull request by Mility**

### CODE REVIEW

**Comment by danielnaber** [comment]
This test fails for me: `assertGood("The can can hold the water.")`, I guess `disambiguation.xml` needs to be modified, too? Then it should be part of the patch. Also, please use 2 spaces for indentation, not tabs.

**Comment by Mility** [comment]
the disambiguation.xml has updated in a new pull request.

**Comment by danielnaber** [comment]
I cannot see any new pull request at https://github.com/languagetool-org/languagetool/pulls

**Comment by Mility** [comment]
please see at https://github.com/Mility/languagetool/pull/3

**Comment by danielnaber** [comment]
I get syntax errors because of the `<and>` in the XML, but when I remove that I get this in `EnglishDisambiguationRuleTest`:

    CAN_WILL_MD:1 can[can/MD,can/NN,can/VB,can/VBP,O] -> can[can/MD,O] 
    Expected :can[can/MD,can/NN,can/VB,can/VBP]
    Actual   :can[can/MD]

Did you make sure all existing tests still work? Remember that disambiguation rules are not independent like error matching rules, they can influence each other depending on their order.

**Comment by Mility** [comment]
Sorry, on the beginning, I just made EnglishWordRepeatRuleTest, and today I made a EnglishDisambiguationRuleTest and found problem like you.

**Comment by danielnaber** [comment]
Thanks, I've simplified the patch a bit (only one `posIsIn()` method) and committed it.

**Pull request closed without merging**
