### PR TITLE
Fix for issue #4585

### PR DESCRIPTION
**Pull request by l3043Y**

### CODE REVIEW

**Comment by jaumeortola** [comment]
We can remove the undesired tags in `shan't` and `can't` with a simple disambiguation rule, and I think it is better to do it this way. 

We prefer not to add complexity to the tokenizer. It is critical for us that the tokenizer is as fast as possible.

**Comment by jaumeortola** [comment]
Fixed here: https://github.com/languagetool-org/languagetool/commit/086385ba520ea5e35453759baa34aafcdf28370f

**Comment by l3043Y** [comment]
Thank you for your comment. I hope to come up with elegant fixes later on, and minimal function complexity.

**Comment by jaumeortola** [comment]
Thank you for your work.

**Pull request closed without merging**
