### PR TITLE
German tagger improvement for dash-linked words

### PR DESCRIPTION
**Pull request by nopepper**
Sorry about the new pull request. I seem to have messed up the old one.
Here is the modified class with the requested changes and unit test.

### CODE REVIEW

**Comment by f-knorr** [comment]
Hi @nopepper ! Thank you! I think that's a great contribution to LT.

**Comment by f-knorr** [comment]
Hi @nopepper ! I have reverted the pull request due to a lot of errors in the regression test (see https://languagetool.org/regression-tests/20170918/result_de_20170918.html) I suggest we wait until after the release of the new LT-version (end of september) and then we see what has to be done to turn of these false positives (maybe it's enough to add an exception to DE_CASE rule for adjektives containing '-')

**Comment by f-knorr** [comment]
I think it is pretty easy to define antipatterns so that DE_CASE-rule does not trigger for the tagged compounds. The tagging needs some refinement, too: I think compounds with a leading number (1930-er or 5-fache) should be ignored.

**Comment by nopepper** [comment]
Thanks, noted.

**Comment by f-knorr** [comment]
I have added some test for DE_CASE-rule (eedc0e6) and an exception which would turn off errors for upper-cased compounds (6982a5e) such as UV-bestrahlt etc.

**Comment by f-knorr** [comment]
When it comes to some nouns, your approach will create false tagging:

- Das Entweder-oder, das Teils-teils, das Sowohl-als-auch, das Als-ob
- Ich habe Du-weißt-schon-wen getroffen

**Pull request merged**
