### PR TITLE
[pt-PT] Improved rule ID:PRAZER_EM_CONVIDAR

### PR DESCRIPTION
**Pull request by marcoagpinto**
Heya,

Rule improved but still zero hits in the 900 000 corpora.

### CODE REVIEW

**Review by p-goulart — APPROVED** [review]
Out of curiosity, is there *really* a difference in formality in `pt-PT` between "ter prazer em convidá-la" and "ter gosto em convidá-la"? To me it sounds backwards.

**Comment by marcoagpinto** [comment]
> Out of curiosity, is there _really_ a difference in formality in `pt-PT` between "ter prazer em convidá-la" and "ter gosto em convidá-la"? To me it sounds backwards.

@p-goulart 
Yes, “gosto” is the right word.

While I worked for the university, its administrator said something like: “Eu teria o maior prazer em blah blah” and the director corrected him: “Não se diz prazer, mas gosto”.

**Comment by marcoagpinto** [comment]
@p-goulart 

HELP!!!! (again)

It has conflicts.

Thanks!

**Comment by marcoagpinto** [comment]
Ahhh… I repulled it, and merged it.

I also realised that the rule should work with any verb instead of just “convidar”… it is in my TODO list.

**Pull request closed without merging**
