### PR TITLE
[ru]update unification

### PR DESCRIPTION
**Pull request by kostyfisik**
@yakovru  Update unification pattern to cover
NN:Fem:Sin
NNF:Nom:PL
NN:Masc:PL:Nom:Talk
(Sin and PL can be the last specifier, case (e.g. Nom) can be second and not the last)

Added PL to gender unification group, otherwise correct cases similar to
PT:Past:PL  NN:Masc:PL:.*     (e.g. манящие очи)
ADJ:PL:.* NN:Masc:PL:.*     (зелёные карандаши )
(or Fem or Neut) will be marked as wrong with gender unification rule (there is no .*:Masc(.*) in first token)
 or even
ADJ:PL:Nom  NN::PL:Nom   (зелёные ножницы)

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
have the right to submit it under the open source license
indicated in the file; or

(b) The contribution is based upon previous work that, to the best
of my knowledge, is covered under an appropriate open source
license and I have the right under that license to submit that
work with modifications, whether created in whole or in part
by me, under the same open source license (unless I am
permitted to submit under a different license), as indicated
in the file; or

(c) The contribution was provided directly to me by some other
person who certified (a), (b) or (c) and I have not modified
it.

(d) I understand and agree that this project and the contribution
are public and that a record of the contribution (including all
personal information I submit with it, including my sign-off) is
maintained indefinitely and may be redistributed consistent with
this project or the open source license(s) involved.

Signed-off-by: Konstantin Ladutenko <kostyfisik@gmail.com>

### CODE REVIEW

**Comment by kostyfisik** [comment]
Hmm.. Gender and number unification can be tricky. E.g.
CORRECT В комнате стояли деревянные стол и стул
CORRECT В комнате стояли деревянный стол и железный стул
How to unify verb, adj, and noun?
e.g. 
WRONG  В комнате стоял деревянный стол и стул

**Comment by yakovru** [comment]
The best way to simplify unification is rebuild dictionary with new postag for adjectives (like ADJ:Masc:Sin:Nom). But after that we need change grammar.xml and other files.
Or we need write more complex rule for unification.

**Comment by kostyfisik** [comment]
@yakovru  Please, review my changes and let my know if I need to change something to make it even better. To my option unification declarations in the current PR should be quite general to be independent of exact tagging scheme (while tags Masc, Fem, Sin, PL and so on are in use).

Unifying the tagging scheme itself can be a two steps process: 1) move all word agreement rules to unification tags. 2) Change tagging dictionary. 

Moreover, some rules will still work with new tagging scheme as soon as "ADJ:Masc:Sin:Nom" will be matched with postag="ADJ:.*:Nom" or postag="ADJ:Masc:.*" as well. The problem can be with postag="ADJ:PL:.*" with was found 8 times in grammar.xml. Still autoreplace with "ADJ::PL:.*" should to the trick.  This way it should not be extremely difficult.

**Comment by yakovru** [comment]
I need some time to test unification.
After add some unification https://github.com/languagetool-org/languagetool/commit/435bd53cd29a173e75050d4a3108aaffee444194  in grammar.xml  
I got better results on the work of these rules  (see night test result).

**Comment by kostyfisik** [comment]
I have tested this branch on tatoeba file - it gives exactly the same  number of matches (2895 total matches). Runing ./testrules.sh verifies everything to be ok in Russian. So merging this as it blocks me from working on rules.

**Comment by yakovru** [comment]
Ok.

**Pull request merged**
