### PR TITLE
[es] rule for am/pm abbreviation

### PR DESCRIPTION
**Pull request by tiff**
See https://forum.languagetool.org/t/es-usage-of-am-pm/4522

### CODE REVIEW

**Comment by fitojb** [comment]
I was wondering if this could be made so that the abbreviation is spaced with non-breaking spaces? Like so: _a.&nbsp;m., p.&nbsp;m._

**Comment by tiff** [comment]
Hi @fitojb. Sure, I'm not familiar with Spanish grammar but if you could give some insights why there needs to be a space in between I would be happy to implement this change

**Comment by fitojb** [comment]
We add a space because each abbreviated letter belongs to a different word (respectively, _ante meridiem_ or _post meridiem_). Further examples:
* _que en paz descanse → q. e. p. d._
* _visto bueno → v.º b.º_
* _nota del traductor → N. del T._
* _por ejemplo → p. ej._

The only abbreviations that do not use a space are those written with a slash (which are few): _sin número → s/n_ or _s. n._ We also do not use spaces in initialisms: _ONU_ (UN); _OTAN_ (NATO), etc.

**Comment by tiff** [comment]
@fitojb done. See https://github.com/languagetool-org/languagetool/commit/3548c9a5c36dc425506eb0301b6cb0d639e2d661

Are you interested in contributing rules to the Spanish version of LT? We are in need of someone maintaining and growing the rule set.

**Pull request merged**
