### PR TITLE
[en] daytime one word

### PR DESCRIPTION
**Pull request by AzadehSafakish**
You should go during the day time. → You should go during the daytime.

### CODE REVIEW

**Comment by AzadehSafakish** [comment]
moved to grammar category

**Comment by tiff** [comment]
There's even a COMPOUNDING category :)

**Comment by AzadehSafakish** [comment]
Moved once again XD

**Comment by udomai** [comment]
Merged here: https://github.com/languagetool-org/languagetool/commit/8c3dd5fd3525b07ba5224e78ed4bc24fdaf8ab94

**Pull request closed without merging**
