### PR TITLE
[pt] Removed rule ID:MADRUGADA_MATINAL

### PR DESCRIPTION
**Pull request by marcoagpinto**
Heya, @p-goulart and @susanaboatto 

I have removed this useless rule.

😛 😛 😛 😛 😛 😛

### CODE REVIEW

**Comment by p-goulart** [comment]
Tbh I like this as a style rule... it does confer the text a more polished feel to say 'a neblina matinal' rather than 'a neblina da manhã'. The one exception would be café, at least in Brazil, since there 'café da manhã' is lexicalised as 'breakfast'. Personally I wouldn't remove it.

**Comment by marcoagpinto** [comment]
> Tbh I like this as a style rule... it does confer the text a more polished feel to say 'a neblina matinal' rather than 'a neblina da manhã'. The one exception would be café, at least in Brazil, since there 'café da manhã' is lexicalised as 'breakfast'. Personally I wouldn't remove it.

@p-goulart 
I had the same feeling about the rule, but I wasn't sure.

I sometimes need a guiding hand to achieve things.

😛 😛 😛 😛 😛 😛 

I will readd it tonight with “café” disabled.

Thank you!

**Comment by marcoagpinto** [comment]
@p-goulart 

Thank you!

I have readded the rule with “café” removed.

❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Review by p-goulart — APPROVED** [review]
LGTM; btw, I think we could use the same rule for `da tarde` -> `vespertino` and `da noite` -> `noturno`.

**Comment by marcoagpinto** [comment]
> LGTM; btw, I think we could use the same rule for `da tarde` -> `vespertino` and `da noite` -> `noturno`.

Sure, I will work on it during the week or on the weekend.

It is an excellent idea!

**Pull request merged**
