### PR TITLE
[pt] Move two rules to dialect-specific grammar files

### PR DESCRIPTION
**Pull request by p-goulart**
- the offending rules had pt-PT specific terminology and examples;
- closes languagetooler-gmbh/languagetool-premium#5571.

### CODE REVIEW

**Comment by p-goulart** [comment]
No idea why the workflow is failing at that specific stage, it's only three grammar files and everything seems to compile locally; @susanaboatto anything obvious? Before I ping devops maybe we can pinpoint a glaring error somewhere.

**Comment by susanaboatto** [comment]
I don't see anything obvious in your changes that could be causing this failure 🤔

**Comment by p-goulart** [comment]
@fabrichter are you the right person to ask for help here? 🧐

**Comment by SteVio89** [comment]
build fixed by https://github.com/languagetool-org/languagetool/commit/3a996d692fa2a877693b90a3b9aad6404293f85a

**Pull request merged**
